### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by thunder95** [yeyupiaoling/PaddlePaddle-DeepSpeech#1]
请问夜雨飘零大神有预训练模型吗， 试了下paddle官方的预训练模型效果不太理想。

**Comment by yeyupiaoling** [comment]
@thunder95 没有呢，我的机器训练起来很慢

**Comment by yeyupiaoling** [comment]
@thunder95 我临时提供了一个模型，在文档的最后可以下载。
