### ISSUE TITLE
python generate_audio.py运行报错 parakeet.frontend.cn_frontend 找不到

### ISSUE THREAD

**Issue by conquer66666** [yeyupiaoling/PaddlePaddle-DeepSpeech#104]
DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 111] Connection refused>
[nltk_data] Error loading cmudict: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
Traceback (most recent call last):
  File "/home/user/test/PaddlePaddle-DeepSpeech/tools/generate_audio/generate_audio.py", line 19, in <module>
    from frontend import Frontend
  File "/home/user/test/PaddlePaddle-DeepSpeech/tools/generate_audio/frontend.py", line 8, in <module>
    from parakeet.frontend.cn_frontend import Frontend as cnFrontend
ModuleNotFoundError: No module named 'parakeet.frontend.cn_frontend'

**Comment by yJun-Chen** [comment]
ModuleNotFoundError: No module named 'parakeet'
是需要安装parakeet还是paddle-parakeet
我安装parakeet的时候显示，parakeet是python2的，使用python3无法安装
然后我安装了paddle-parakeet

再接着一下，出现
```
  File "/root/.paddlehub/modules/fastspeech2_baker/module.py", line 24, in <module>
    from parakeet.frontend.zh_frontend import Frontend
ModuleNotFoundError: No module named 'parakeet.frontend.zh_frontend'
```

请问parakeet.frontend.zh_frontend现在是又更改了么？
