### ISSUE TITLE
快速预测请教

### ISSUE THREAD

**Issue by AlisaChen98** [yeyupiaoling/PaddlePaddle-DeepSpeech#109]
想请教下按照tutorial进行快速预测，执行export_model.py的时候报错FileNotFoundError: [Errno 2] No such file or directory: './dataset/zh_vocab.txt'。这个文件的用处是什么呢，看repo里没有，如何解决这个问题呀

**Comment by wending0417** [comment]
你好，请问后来是怎么解决的呀？
