### ISSUE TITLE
静态图动态图模型收敛速度差异

### ISSUE THREAD

**Issue by zhangyifei1** [yeyupiaoling/PaddlePaddle-DeepSpeech#113]
大佬，你写的静态图和动态图模型我都在使用，但是在训练的时候有个疑问。相同的数据、字典、标准化值，在训练的时候收敛的速度很不一样，请问下这是什么原因。
图一是静态图下2个epoch的loss以及test cer。
![图片](https://user-images.githubusercontent.com/28425091/143539822-ab945383-8c1f-49db-a599-3f3414fd83d5.png)
图二是动态图下20个epoch的loss以及test cer。
![图片](https://user-images.githubusercontent.com/28425091/143540120-74b823bd-d6c3-45ed-a216-ec597ebba04d.png)

**Comment by yeyupiaoling** [comment]
模型结构不是完全对齐的，这个项目下的准确率更好些。
