### ISSUE TITLE
关于合成语音数据集

### ISSUE THREAD

**Issue by uloveqian2021** [yeyupiaoling/PaddlePaddle-DeepSpeech#114]
“tools/generate_audio/speaker_audio目录下，开发者也可以尝试入自己的音频放入该目录，这样训练出来的模型能更好识别开发者的语音，采样率最好是16000Hz” 
大佬，您好，请问要怎么合成自己声音的数据集，我看当前的 generate_audio.py 代码中没有用到speaker_audio目录下的音频，希望能指导一下，谢谢！

**Comment by yeyupiaoling** [comment]
这个不支持声音克隆，只能通过这种方式设置说话人。
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/eb518cd14a0288b7d2b5a457cb4ff3ae4a9a6e59/tools/generate_audio/generate_audio.py#L88
