### ISSUE TITLE
运行infer_path 没有出现结果

### ISSUE THREAD

**Issue by anip1648** [yeyupiaoling/PaddlePaddle-DeepSpeech#117]
![1638341415(1)](https://user-images.githubusercontent.com/79182463/144185902-36aa35e6-88cb-4168-84d8-ed4249d8481b.png)

**Comment by anip1648** [comment]
不知道那个库没有加载

**Comment by yeyupiaoling** [comment]
你能使用GPU推理一次看看吗？

**Comment by anip1648** [comment]
可以了，谢谢

**Comment by Xjorker** [comment]
请问怎么解决的

**Comment by yeyupiaoling** [comment]
@Xjorker 你的报什么错误
