### ISSUE TITLE
音频长度大于15

### ISSUE THREAD

**Issue by lfxx** [yeyupiaoling/PaddlePaddle-DeepSpeech#12]
目前手里的数据集音频长度都是大于15s的，batch_size设置成16的话就爆显存，然后就设置了batch_size=8,结果就碰到了loss=nan问题，想知道有方法能对长音频进行分割吗，现在几乎无法训练了

**Comment by lfxx** [comment]
> 目前手里的数据集音频长度都是大于15s的，batch_size设置成16的话就爆显存，然后就设置了batch_size=8,结果就碰到了loss=nan问题，想知道有方法能对长音频进行分割吗，现在几乎无法训练了

搞不懂为啥batch_size设置小点，loss就是nan了，玄学

**Comment by yeyupiaoling** [comment]
@lfxx 分割音频恐怕不容易，也不好，因为每条语音可能都是完整的一句话。

**Comment by yeyupiaoling** [comment]
@lfxx 这个好理解，你batch_size设置小了，但是学习率不变，那就很容易学崩

**Comment by yeyupiaoling** [comment]
语音识别模型对显存要求很高，3090就不错，有24G显存。

**Comment by lfxx** [comment]
> @lfxx 分割音频恐怕不容易，也不好，因为每条语音可能都是完整的一句话。

那只要学习率设置小点，就可以成功训练了吧，我目前学习率设置为1e-5,还是nan.再小十倍或许可以？

**Comment by lfxx** [comment]
> 语音识别模型对显存要求很高，3090就不错，有24G显存。

我这rtx2080ti这的尴尬，动不动爆显存

**Comment by yeyupiaoling** [comment]
>那只要学习率设置小点，就可以成功训练了吧，我目前学习率设置为1e-5,还是nan.再小十倍或许可以？

应该可以，试试

**Comment by yeyupiaoling** [comment]
>我这rtx2080ti真的尴尬，动不动爆显存

我的也是2080ti，很难搞。

**Comment by lfxx** [comment]
> > 那只要学习率设置小点，就可以成功训练了吧，我目前学习率设置为1e-5,还是nan.再小十倍或许可以？
> 
> 应该可以，试试

太小会不会造成后期无法收敛?

**Comment by yeyupiaoling** [comment]
多少张卡

**Comment by lfxx** [comment]
> 多少张卡

2张

**Comment by yeyupiaoling** [comment]
>太小会不会造成后期无法收敛?

是的，我一般是5分之一下降测试的

**Comment by yeyupiaoling** [comment]
>2张

我也是

**Comment by lfxx** [comment]
> > 太小会不会造成后期无法收敛?
> 
> 是的，我一般是5分之一下降测试的

具体怎么操作呢，这个下降测试

**Comment by yeyupiaoling** [comment]
>具体怎么操作呢，这个下降测试

比如现在是5-e-5，出现了nan，就停止训练，测试1e-6学习率，这样测试

**Comment by yeyupiaoling** [comment]
你的语音是啥，一句话有这么长的？

**Comment by lfxx** [comment]
> 你的语音是啥，一句话有这么长的？

方便加微信交流吗

**Comment by yeyupiaoling** [comment]
号码:qq945772813
