### ISSUE TITLE
可以离线使用吗？

### ISSUE THREAD

**Issue by coderyiyang** [yeyupiaoling/PaddlePaddle-DeepSpeech#122]
可以离线使用吗？

**Comment by yeyupiaoling** [comment]
你说的离线是什么意思？

**Comment by coderyiyang** [comment]
> 你说的离线是什么意思？

就是在不联网的情况下完成语音转文字

**Comment by yeyupiaoling** [comment]
本来就不用联网的。

**Comment by coderyiyang** [comment]
老哥可以给个AISHELL训练好的模型吗？csdn要买会员

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："夜雨飘零 ***@***.***&gt;;
发送时间：2021年12月15日(星期三) 晚上11:08
收件人："yeyupiaoling/PaddlePaddle-DeepSpeech" ***@***.***&gt;;
抄送："coderyiyang ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] 可以离线使用吗？ (Issue #122)
-----------------------------------

 

 本来就不用联网的。

**Comment by yeyupiaoling** [comment]
不用啊，可以直接下载

**Comment by coderyiyang** [comment]
下下来了一个ds2.model，解压出来三个文件夹，conf, data, exp，这些文件夹放哪儿呀老哥

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："夜雨飘零 ***@***.***&gt;;
发送时间：2021年12月16日(星期四) 晚上10:40
收件人："yeyupiaoling/PaddlePaddle-DeepSpeech" ***@***.***&gt;;
抄送："coderyiyang ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] 可以离线使用吗？ (Issue #122)
-----------------------------------

 

 
不用啊，可以直接下载

**Comment by yeyupiaoling** [comment]
你下载的是什么，我项目没有这些东西的

**Comment by coderyiyang** [comment]
我在https://paddlespeech.bj.bcebos.com/s2t/aishell/asr0/ds2.model.tar.gz下载的。您项目里用
AISHELL数据集训练的模型指向了一个付费的csdn链接。在这里：https://download.csdn.net/download/qq_33200967/15902032









----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："夜雨飘零 ***@***.***&gt;;
发送时间：2021年12月16日(星期四) 晚上10:48
收件人："yeyupiaoling/PaddlePaddle-DeepSpeech" ***@***.***&gt;;
抄送："coderyiyang ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] 可以离线使用吗？ (Issue #122)
-----------------------------------

 

 
你下载的是什么，我项目没有这些东西的

**Comment by yeyupiaoling** [comment]
你下载的那个模型，不是我项目的，
这个不是付费的，你看清楚。

**Comment by coderyiyang** [comment]
是我错了，感谢感谢！

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："夜雨飘零 ***@***.***&gt;;
发送时间：2021年12月16日(星期四) 晚上10:54
收件人："yeyupiaoling/PaddlePaddle-DeepSpeech" ***@***.***&gt;;
抄送："coderyiyang ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] 可以离线使用吗？ (Issue #122)
-----------------------------------

 

 
你下载的那个模型，不是我项目的，
 这个不是付费的，你看清楚。

**Comment by coderyiyang** [comment]
Out of memory error on GPU 0. Cannot allocate 323.716064MB memory on GPU 0, 1.837984GB memory has been allocated and available memory is only 165.904686MB.


哥，这个报错怎么搞

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："夜雨飘零 ***@***.***&gt;;
发送时间：2021年12月16日(星期四) 晚上10:54
收件人："yeyupiaoling/PaddlePaddle-DeepSpeech" ***@***.***&gt;;
抄送："coderyiyang ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] 可以离线使用吗？ (Issue #122)
-----------------------------------

 

 
你下载的那个模型，不是我项目的，
 这个不是付费的，你看清楚。

**Comment by coderyiyang** [comment]
在哪个地方调batch_size?

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："夜雨飘零 ***@***.***&gt;;
发送时间：2021年12月16日(星期四) 晚上10:54
收件人："yeyupiaoling/PaddlePaddle-DeepSpeech" ***@***.***&gt;;
抄送："coderyiyang ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] 可以离线使用吗？ (Issue #122)
-----------------------------------

 

 
你下载的那个模型，不是我项目的，
 这个不是付费的，你看清楚。

**Comment by yeyupiaoling** [comment]
train.py
