### ISSUE TITLE
可以不保存wav文件直接用麦克风阵列数据预测吗？

### ISSUE THREAD

**Issue by thunder95** [yeyupiaoling/PaddlePaddle-DeepSpeech#123]
我看代码里都是先录制音频文件再保存，可以不用保存将帧数据直接送到网络预测吗？

**Comment by yeyupiaoling** [comment]
这个项目支持直接输入流的：
https://github.com/yeyupiaoling/PPASR/blob/8d49e8f532d8581f7d1847fb687ce13ffc7687b8/infer_gui.py#L203

**Comment by thunder95** [comment]
@yeyupiaoling 大佬太强了，项目写得太棒了 我得好好学习学习
