### ISSUE TITLE
运行“export_model.py”时出现版本不匹配问题

### ISSUE THREAD

**Issue by Aulon13** [yeyupiaoling/PaddlePaddle-DeepSpeech#124]
在命令提示符下，检测paddle的运行无任何问题，
![111](https://user-images.githubusercontent.com/95991130/146487767-c641668c-8616-4093-b52f-dcbb550e1ba4.png)

但在vs code的终端运行export_model.py文件时报错！
![222](https://user-images.githubusercontent.com/95991130/146487791-370b77cb-2268-4aed-86d4-b869f828e94e.png)

**Comment by yeyupiaoling** [comment]
看错误提示是你的GPU环境有问题。用anconda安装吧

**Comment by Aulon13** [comment]
@yeyupiaoling 刚才我用命令提示符来导出模型，出现了新的问题提。说模型恢复的路径参数不存在？
![image](https://user-images.githubusercontent.com/95991130/146500259-dd042383-26c0-4a47-bc25-2cafe8850e0c.png)

**Comment by yeyupiaoling** [comment]
你下载模型放在对应的位置了吗？或者你训练模型了吗？
