### ISSUE TITLE
dict_size = 0  是不是配置有错误？

### ISSUE THREAD

**Issue by jeffzhengye** [yeyupiaoling/PaddlePaddle-DeepSpeech#125]
初始化解码器...                                                                                                                                                         ======================================================================                                                                                                  language model: is_character_based = 1, max_order = 5, dict_size = 0                                                                                                    ======================================================================

我检查了，lm 模型，zh_vocab 路径都是没有问题的。

**Comment by yeyupiaoling** [comment]
这是正常输出啊，有报什么错吗？

**Comment by jeffzhengye** [comment]
dict_size = 0 ， 这个时什么词典的size啊？

**Comment by yeyupiaoling** [comment]
这个只是解码器的初始化输出而已，实际是正常的。
