### ISSUE TITLE
能提供一个训练好的模型吗？

### ISSUE THREAD

**Issue by ReBenDish** [yeyupiaoling/PaddlePaddle-DeepSpeech#126]
想要问一下大佬能够提供一个已经训练好的模型吗

**Comment by yeyupiaoling** [comment]
请看文档。

**Comment by ReBenDish** [comment]
> 请看文档。

![image](https://user-images.githubusercontent.com/40975871/146938450-4546f55d-54ce-4c32-8e3d-36cd84ed8c19.png)

**Comment by ReBenDish** [comment]
> 请看文档。

点击下载好像没有反应

**Comment by yeyupiaoling** [comment]
![image](https://user-images.githubusercontent.com/26297768/146939568-90a6c278-6c56-4b3b-b145-32539cb88c22.png)

我的是这样的

**Comment by ReBenDish** [comment]
> ![image](https://user-images.githubusercontent.com/26297768/146939568-90a6c278-6c56-4b3b-b145-32539cb88c22.png)
> 
> 我的是这样的

感觉是csdn和知网一样把你的资源设置为会员了可能。。

**Comment by yeyupiaoling** [comment]
我没用设置，之前其他开发者都能正常下载

**Comment by ReBenDish** [comment]
> 我没用设置，之前其他开发者都能正常下载

也许你也可以起诉CSDN了博主。。你的资源都被CSDN设为VIP资源了
![image](https://user-images.githubusercontent.com/40975871/147025600-f218139c-1110-4d2a-a66c-863f584ee90a.png)

**Comment by yeyupiaoling** [comment]
这个模型是我设置的，但是前面几个我没有设置。还有你看的这个是旧版本的模型，

**Comment by ReBenDish** [comment]
> 这个模型是我设置的，但是前面几个我没有设置。还有你看的这个是旧版本的模型，

嗯，这个我是在下面随便找了一个博主上传的看看，前面几个好像都下不了，博主可以把前面几个发一下我的邮箱吗，万分感谢！
807005320@qq.com

**Comment by Aulon13** [comment]
@yeyupiaoling 我在csdn上面下了一个你训练好的数据集，但测试下来，语音识别的准确率好低，你知道这是为什么吗？

**Comment by yeyupiaoling** [comment]
哪个？你测试的是那个数据集？

**Comment by Aulon13** [comment]
PPASR_大数据集 和 DeepSpeech_thchs30 都测试过了，我用的是infer_server.py网页来测试的，他返回的 文字 和我的语音内容完全不一样，我不知道为什么。

**Comment by Aulon13** [comment]
@yeyupiaoling 如果您现在有时间的话，我愿意花点钱，让您远程为我看看。不知道可以不可以？

**Comment by yeyupiaoling** [comment]
晚上有时间了的话，可以帮你看一下。 你可以先试一下项目本身的音频文件。

**Comment by Aulon13** [comment]
@yeyupiaoling 项目本省的音频 是正确的，但我在网页上用话筒说的就是错误的，但播放出来的声音是正确的。

**Comment by Aulon13** [comment]
@yeyupiaoling 好的，十分感谢，要不先加一下QQ吧？413035425

**Comment by yeyupiaoling** [comment]
现在没时间。

**Comment by Aulon13** [comment]
@yeyupiaoling 嗯，那等你晚上再加吧，多谢。

**Comment by Aulon13** [comment]
@yeyupiaoling 你好，现在有空了吗？：）

**Comment by huanhuan-xiao** [comment]
你好，请问你获取到训练好的模型了吗？我从作者链接下载的data_thchs30训练模型，导出模型测试时，使用不同的语音文件测试结果大致都一样就是几个不连贯的字，得分也比较低。再次导出模型对同一语音文件测试结果又不一样。是模型不对还是哪里需要修改？

**Comment by yeyupiaoling** [comment]
你是测试自己的语音吗？用项目的语音是否正确。

**Comment by huanhuan-xiao** [comment]
不是，就是测试项目自带的test.wav文件

**Comment by yeyupiaoling** [comment]
你有替换全部文件吗，dataset里面的文件。还是说你下载错了模型

**Comment by huanhuan-xiao** [comment]
替换了，我又新建一个，模型是你链接的那个，还是那样的错误。

**Comment by yeyupiaoling** [comment]
我链接哪一个你说嘛，你把之前那些全部删了，重新复制一遍

**Comment by huanhuan-xiao** [comment]
下面的链接，我的数据和模型都是thchs30。
![2022-01-07 08-30-58屏幕截图](https://user-images.githubusercontent.com/82137867/148472124-32dd4c46-be90-4d76-9a50-4ec7c7cf80d0.png)

**Comment by yeyupiaoling** [comment]
你重新解压文件，然后复制全部文件夹，替换项目中的全部文件，重新导出。再试试。

**Comment by yeyupiaoling** [comment]
要不你用这个项目试试：https://github.com/yeyupiaoling/PPASR
