### ISSUE TITLE
是否支持英文 .wav格式转文本

### ISSUE THREAD

**Issue by Jzow** [yeyupiaoling/PaddlePaddle-DeepSpeech#128]
非中文，音频是否支持转换文本

**Comment by Jzow** [comment]
@yeyupiaoling 谢谢你的及时回复，请问是否有了解其他开源库支持

**Comment by yeyupiaoling** [comment]
https://github.com/PaddlePaddle/PaddleSpeech

**Comment by Jzow** [comment]
@yeyupiaoling 谢谢 我研究下
