### ISSUE TITLE
关于中文识别、声纹识别和声音场景分类的咨询

### ISSUE THREAD

**Issue by mocaibupt** [yeyupiaoling/PaddlePaddle-DeepSpeech#13]
你好，非常不好意思打扰你。我想搭建中文识别、说话人识别、声音场景分类这三个的功能项目。然后我找了一些开源库。但因为我之前是一直在开发的方向上走，没有接触过语音这一块。想咨询你几个问题：
1.我使用了官方paddlepaddle-DeepSpeech开源代码搭建了一个baidu1.2k模型的中文语音在线识别系统，但识别效果不是太好。想咨询下你的这个工程在使用baidu1.2k模型和自训练模型的效果如何？或者可以帮忙推荐一个代码和模型都开源的效果比较好的中文识别项目么？
2.声纹识别我也找了一个开源库搭建起来了，但还没有用数据集去测试。想咨询下您基于paddlepaddle的声纹识别的项目效果如何？
3.我看了你其他的两个基于paddlepaddle和TensorFlow的用urbansound8k搭建的声音场景分类工程，想咨询这个的效果怎么样？

非常抱歉打扰您~非常希望你能拨冗给予我一点帮助，谢谢

**Comment by yeyupiaoling** [comment]
@mocaibupt 
我项目中的`baidu1.2k模型`也是官方的，我没有使用过。我的`自训练模型`由于算力不足，还没训练完，所以效果一般般。
我所接触的中文语音识别，这个项目是最好的了，只要数据集和算力够，这个没问题的。

>基于paddlepaddle的声纹识别

这个项目是我用于学习，效果不怎么好，如何要应用的项目中，需要优化模型。

>基于paddlepaddle和TensorFlow的用urbansound8k搭建的声音场景分类工程

这个准确率有80%多，优化模型应该会更高
