### ISSUE TITLE
执行CUDA_VISIBLE_DEVICES=0,1 python train.py

### ISSUE THREAD

**Issue by CbzBack** [yeyupiaoling/PaddlePaddle-DeepSpeech#131]
执行 CUDA_VISIBLE_DEVICES=0,1 python train.py
出现问题：
E0118 17:24:25.459153 227364288 pybind.cc:1620] Cannot use GPU because you have installed CPU version PaddlePaddle.
If you want to use GPU, please try to install GPU version PaddlePaddle by: pip install paddlepaddle-gpu
If you only have CPU, please change CUDAPlace(0) to be CPUPlace().

我修改了文件 train.py 的 
add_arg('use_gpu',          bool,   True,   "是否使用GPU训练") 
变成
add_arg('use_gpu',          bool,   False,   "是否使用GPU训练")

再次执行 CUDA_VISIBLE_DEVICES=0,1 python train.py
提示：
Train [2022-01-19 15:05:11.317693] epoch: [1/50], batch: [0/835], learning rate: 0.00050000, train loss: 1131.456787, eta: 7 days, 11:58:11

在这里就不动了。
请问是否要 7 天才能完成？如果是的话有什么好办法解决么。

**Comment by yeyupiaoling** [comment]
>请问是否要 7 天才能完成？如果是的话有什么好办法解决么。

训练的话，还是要用GPU。

**Comment by CbzBack** [comment]
但是按照这个提示
If you want to use GPU, please try to install GPU version PaddlePaddle by: pip install paddlepaddle-gpu
执行了 pip install paddlepaddle-gpu
出现报错：
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu

查了相关解决方式，都是说把 Python 的版本改成3.7
我在终端输入 python -V，返回 Python 3.7.12

这样应该表示我的环境没有错吧？

**Comment by yeyupiaoling** [comment]
你看官网按照GPU版本的PaddlePaddle
https://www.paddlepaddle.org.cn/

**Comment by CbzBack** [comment]
OK，我知道了。
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/macos-pip.html
这里有了一句：  目前在MacOS环境仅支持CPU版PaddlePaddle

所以 macOS 暂时没办法使用 GPU 训练了。。。
