### ISSUE TITLE
识别结果是乱码

### ISSUE THREAD

**Issue by njuxdj** [yeyupiaoling/PaddlePaddle-DeepSpeech#133]
你好，我的环境是python3.8，模型是下载的DeepSpeech_free_st_chinese_mandarin_corpus，测试数据是/dataset/test.wav，但是运行的识别结果是乱码。请教下可能原因是什么，万分感谢。
root@bogon:~/下载/PaddlePaddle-DeepSpeech-master# python3 infer_path.py --wav_path=./dataset/test.wav --use_gpu=False
/usr/lib/python3/dist-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Callable
/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py:311: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/librosa/core/constantq.py:1058: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
-----------  Configuration Arguments -----------
alpha: 1.2
beam_size: 300
beta: 0.35
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_greedy
enable_mkldnn: False
is_long_audio: False
lang_model_path: ./lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: ./dataset/mean_std.npz
model_dir: ./models/infer/
to_an: True
use_gpu: 0
vocab_path: ./dataset/zh_vocab.txt
wav_path: ./dataset/test.wav
------------------------------------------------
消耗时间：2803ms, 识别结果: 冰脆陆潮氦陆逸谬堰掀粳哪古膀陆乞陆乞哪芳灌锅铡险渥铡灌渥锅瞬京夏曦蝴揶布曼氮陆屋蝴区颚蔫侯篷眬造塘耳古奴援眠托铡王臀托亦刘耒嵩枱攀择漠妧托蔫时鸥氮蝴椰蝴氮楠渥馈八渥昆渥巴渥潭俩猩渥潭璇挤伸区颚膝古篷丐古眠虹泠古跻瑄惫兢妈氮王渥飒疫飒怨篷飒煌零充渥蔫攻蔫氮团耳杳奴眠委托妧托氮螂氮, 得分: 30

**Comment by yeyupiaoling** [comment]
你要把里面解压的文件全部覆盖你原来的文件。然后重新导出模型。


你也可以下载一下其他模型试一下。

**Comment by njuxdj** [comment]
可以识别了，用dataset目录下的test.wav 能正确识别。
我自己录了一段语音，本地识别的效果比较差，在线demo识别的就很准确，https://ppasr.yeyupiaoling.cn/。
想请问下大佬，在线demo用的模型可否开源啊。
还想请问下大佬是否有语种识别的开源项目。

**Comment by yeyupiaoling** [comment]
那个大数据模型就是。你可以去下载。语种没有做。
