### ISSUE TITLE
数据准备出错：无法将段规范化到 -20.000000 dB

### ISSUE THREAD

**Issue by Desmond528** [yeyupiaoling/PaddlePaddle-DeepSpeech#134]
在执行python create_data.py时出错，到显示“开始抽取-1条数据计算均值和标准值”，并进行到255/1625的时候报错
报错信息：
ERROR:root:DataLoader reader thread raised an exception!

ValueError: 无法将段规范化到 -20.000000 dB，因为可能的增益已经超过max_gain_db (300.000000 dB)

[Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
求教这是啥问题

**Comment by Wei-JL** [comment]
请问这个问题是什么原因，我这边是用录音设备录制的？  也是同样的报错

**Comment by Desmond528** [comment]
我没去找问题的原因，就只是把那些有问题的录音文件给丢掉了
