### ISSUE TITLE
train.py运行报错

### ISSUE THREAD

**Issue by Mingjie-Chen** [yeyupiaoling/PaddlePaddle-DeepSpeech#135]
您好，我跟着您发布在Bilibili的视频一步步做下来，发现我在运行train.py时会报错。然后，我也模拟了您的环境，在百度飞桨AI Studio上进行了项目的运行，发现train.py也会报错。报错信息如下，请问是否是代码上存在一些小问题。我是初学者，不太清楚怎么解决这个问题，麻烦您不吝赐教。
![image](https://user-images.githubusercontent.com/79888535/155317727-1383888d-bf35-42aa-a7b4-88ce7966174d.png)

**Comment by yeyupiaoling** [comment]
@Mingjie-Chen 看日志输出，应该是数据有问题，你查看下是否是数据集路径不正确。

也可以看这个项目：https://github.com/yeyupiaoling/PPASR
这个简单些，

**Comment by Mingjie-Chen** [comment]
解决了，感谢回复和分享源代码。
