### ISSUE TITLE
缺少 paddlespeech-ctcdecoders 库，请安装，如果是Windows系统，只能使用ctc_greedy。 【注意】已自动切换为ctc_greedy解码器。

### ISSUE THREAD

**Issue by zyd-123** [yeyupiaoling/PaddlePaddle-DeepSpeech#138]
![image](https://user-images.githubusercontent.com/83893684/161994193-848e44b2-467e-4f79-a53a-14a3344299b0.png)
缺少 paddlespeech-ctcdecoders 库，请安装，如果是Windows系统，只能使用ctc_greedy。
【注意】已自动切换为ctc_greedy解码器。

**Comment by yeyupiaoling** [comment]
这不是错误，这只是一个警告。如果是Linux可以用命令
pip install paddlespeech-ctcdecoders

**Comment by zhangzuoxing** [comment]
> 这不是错误，这只是一个警告。如果是Linux可以用命令 pip install paddlespeech-ctcdecoders==0.1.1

安装了版本是0.2.1，这个解码库与版本有关系吗，依然不识别，还是出现这个警告。主要想用语言模型来降低字错率?

**Comment by yeyupiaoling** [comment]
这个不是报错，这个只是警告提示。
