### ISSUE TITLE
在Windows上运行create_data.py报错：Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by liuqizhilqz** [yeyupiaoling/PaddlePaddle-DeepSpeech#139]
经调试，发现在normalizer.py 中"for std1, means1, number1 in tqdm(test_loader()):"这行代码运行完成时显示错误，想问下作者，该如何解决，谢谢

**Comment by yeyupiaoling** [comment]
没有其他错误信息吗？

**Comment by liuqizhilqz** [comment]
作者你好，没有其他错误信息，调试之后，显示的还是Process finished with exit code -1073741819 (0xC0000005) 这个错误。







没有其他错误信息，调试之后，发现这行代码运行之后就报错了，Process finished with exit code -1073741819 (0xC0000005) 。




在 2022-04-08 16:33:05，"夜雨飘零" ***@***.***> 写道：

没有其他错误信息吗？

**Comment by yeyupiaoling** [comment]
你检查看数据是否存在和是不是内存不足了

**Comment by liuqizhilqz** [comment]
作者您好，针对上次的问题，参照网上的解决方案，将将Scipy降版本到1.3.1，这个问题就解决了，谢谢。



在 2022-04-08 17:37:36，"百度" ***@***.***> 写道：







好的，感谢作者，后续我将结果在反馈给您，谢谢










在 2022-04-08 17:09:53，"夜雨飘零" ***@***.***> 写道：

你检查看数据是否存在和是不是内存不足了

**Comment by liuqizhilqz** [comment]
好的，感谢作者，后续我将结果在反馈给您，谢谢










在 2022-04-08 17:09:53，"夜雨飘零" ***@***.***> 写道：

你检查看数据是否存在和是不是内存不足了
