### ISSUE TITLE
预测模型报错

### ISSUE THREAD

**Issue by eclwu** [yeyupiaoling/PaddlePaddle-DeepSpeech#141]
作者，您好，我想请教下
我下载了aishell这个模型，运行infer_gui.py这个文件时报了一个错：ValueError: operands could not be broadcast together with shapes (161,838) (39,1)，这是什么原因，我把dataset里面的两个文件zh_vocab.txt和mean_std.npz都替换了，不知道哪里还出了问题

**Comment by yeyupiaoling** [comment]
你看看是不是下载错误了，要在项目的主要点击下载
