### ISSUE TITLE
过拟合问题吗？

### ISSUE THREAD

**Issue by real-CLiang** [yeyupiaoling/PaddlePaddle-DeepSpeech#148]
您好，我在仅使用thchs_30数据集训练50个epoch后，使用自己制作的测试用例进行预测，发现预测效果很差，而使用您所提供的测试用例进行预测效果很好，请问是什么原因导致这样的情况？
![1](https://user-images.githubusercontent.com/104819352/175525366-9a5adcd3-b527-49b3-9462-42d1567a6286.png)

![2](https://user-images.githubusercontent.com/104819352/175525383-8f42d238-d6eb-48e6-a15b-03f3ca5be435.png)

**Comment by yeyupiaoling** [comment]
可以理解为过拟合。因为你的数据跟那个数据集的分布不太一样。你要预测自己的数据的话，要使用自己的数据集去训练。

**Comment by real-CLiang** [comment]
好的，谢谢您的解答！
十分欣赏您在paddlepaddle框架学习上做出的开源贡献！

**Comment by yeyupiaoling** [comment]
哈哈，
