### ISSUE TITLE
安装python-Levenshtein==0.12.2报错

### ISSUE THREAD

**Issue by ramossky** [yeyupiaoling/PaddlePaddle-DeepSpeech#149]
conda 安装requirements库的时候Levenshtein，webrtcvad，pyaudio都报error

**Comment by yeyupiaoling** [comment]
你的系统是什么？执行命令是什么？

**Comment by ramossky** [comment]
![image](https://user-images.githubusercontent.com/49336642/177487752-cf806b59-70b5-4026-bc54-92bf03bb8dce.png)
win10x64啊，这个错是什么原因？

**Comment by yeyupiaoling** [comment]
这个缺失C++编译环境，安装Visual Studio 就可以了
