### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by zcswdt** [yeyupiaoling/PaddlePaddle-DeepSpeech#15]
您好，按照readme中指示，在执行测试时候，报错。
![image](https://user-images.githubusercontent.com/43515926/110288722-6adcd480-8023-11eb-95ef-44b73e4aba7a.png)

**Comment by yeyupiaoling** [comment]
@zcswdt 你没有成功执行setu.sh这个文件，所以你的ctc解码没有安装

**Comment by zcswdt** [comment]
> @zcswdt 你没有成功执行setu.sh这个文件，所以你的ctc解码没有安装

谢谢回复，我是按照readme中指示执行了sh setup.sh这个文件啊，但是会报错啊。可以+V请教一下么

![image](https://user-images.githubusercontent.com/43515926/110297364-5c47ea80-802e-11eb-83fe-aef7e73913f2.png)

**Comment by yeyupiaoling** [comment]
@zcswdt 在安装的时候出错了，你往上看是哪里导致错误的？提供你的V，我加你

**Comment by zcswdt** [comment]
> 你往上看是哪里导致错误的？提供你的V，我加你

jh201466，多谢大佬

**Comment by ilove-Moretz** [comment]
> 
> 
> > 你往上看是哪里导致错误的？提供你的V，我加你
> 
> jh201466，多谢大佬

嘿，我安装的ctc的时候也遇到了相同的报错，请问这个错误最后怎么解决的？

**Comment by ilove-Moretz** [comment]
> 
> 
> @zcswdt 在安装的时候出错了，你往上看是哪里导致错误的？提供你的V，我加你

嘿，我在安装的时候也遇到了相同的问题，请问这份问题是怎么解决的？

**Comment by ilove-Moretz** [comment]
我解决了这个问题，方法：把PaddlePaddle的DeepSpeechhttps://github.com/PaddlePaddle/DeepSpeech拉下来，运行他的setup.sh脚本，解决了这个问题
