### ISSUE TITLE
python create_data.py 这一步没有生成mean_std.npz

### ISSUE THREAD

**Issue by mufenglalala** [yeyupiaoling/PaddlePaddle-DeepSpeech#152]
执行normalizer的for std1, means1, number1 in tqdm(test_loader()):这个循环以后就直接停止程序运行了

**Comment by yeyupiaoling** [comment]
升级下scipy就可以了，我的是1.9.1

**Comment by mufenglalala** [comment]
> 升级下scipy就可以了，我的是1.9.1

好的谢谢！
