### ISSUE TITLE
识别效果实在不敢恭维

### ISSUE THREAD

**Issue by zhonghui001** [yeyupiaoling/PaddlePaddle-DeepSpeech#153]
![image](https://user-images.githubusercontent.com/7400888/205430326-dc2e08ff-c0fc-4a42-b0f2-b3eba12794ec.png)

**Comment by yeyupiaoling** [comment]
主要是训练的数据集比较小，你可以训练一个大的数据集，例如Wenetspeech。
你也可以用PPASR项目，这个效果更好。
