### ISSUE TITLE
中英文混合语音识别

### ISSUE THREAD

**Issue by mufenglalala** [yeyupiaoling/PaddlePaddle-DeepSpeech#154]
大大我看您在数据准备那里说，数据集里面只能是纯中文：“每一行数据包含该语音文件的相对路径和该语音文件对应的中文文本，要注意的是该中文文本只能包含纯中文，不能包含标点符号、阿拉伯数字以及英文字母”。想问问这个模型可以训练中英文混合的数据集吗？不能的话有推荐的混合语言语音识别的开源模型吗？辛苦大大，感激不尽

**Comment by yeyupiaoling** [comment]
有英文字母也是可以的。但是单词就不行了。

**Comment by yeyupiaoling** [comment]
另外建议你用PPASR

**Comment by Marple-user** [comment]
将之前训练好的模型作为预训练模型，重新追加数据进行训练，新的模型对之前训练数据识别效果不好是什么原因呢

**Comment by yeyupiaoling** [comment]
你要了解使用预训练模型训练和微调。
如果你使用预训练模型重新训练的话。那模型肯定会偏向你的数据集。
没有什么追加训练可说。
