### ISSUE TITLE
关于追加训练

### ISSUE THREAD

**Issue by Marple-user** [yeyupiaoling/PaddlePaddle-DeepSpeech#155]
将之前训练好的模型作为预训练模型，重新追加数据进行训练，怎么样才能保留之前的效果

**Comment by Marple-user** [comment]
词汇列表更新未出现的字符，mean_std.npz也进行更新过，你每次追加后都会影响之前的结果，只能将之前训练过的数据集结合一起这种方法吗

**Comment by yeyupiaoling** [comment]
你可以只在你的数据集训练几轮就可以了。不能训练的太多。

**Comment by Marple-user** [comment]
训练轮次少了能识别到我的数据吗，追加训练不就是保留之前的能力学习新的能力吗

**Comment by yeyupiaoling** [comment]
不会保留，模型会拟合你的新数据

**Comment by Marple-user** [comment]
好的，谢谢
