### ISSUE TITLE
本地预测出现问题

### ISSUE THREAD

**Issue by linlin6090** [yeyupiaoling/PaddlePaddle-DeepSpeech#157]
大佬您好！抱歉打扰您了，我按照步骤下载了您的源码和对应的模型aishell，复制并替换了全部的文件，然后导出了模型，进行本地预测为啥会显示得分0，啥也预测不出来的情况
-----------  Configuration Arguments -----------
alpha: 1.2
beam_size: 300
beta: 0.35
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_greedy
is_long_audio: False
lang_model_path: ./lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: ./dataset/mean_std.npz
model_dir: ./models/infer/
to_an: True
use_gpu: True
vocab_path: ./dataset/zh_vocab.txt
wav_path: ./dataset/test.wav
------------------------------------------------
消耗时间：185ms, 识别结果: , 得分: 0

**Comment by yeyupiaoling** [comment]
有正确导出模型吗？
建议你用PPASR项目

**Comment by linlin6090** [comment]
改用cpu后就可以了（gpu预测不知道是因为什么问题），大佬有没有能更准确输出纯英文和数字的项目，不需要语义的那种

**Comment by yeyupiaoling** [comment]
这么神奇，
有数据集就可以训练

**Comment by linlin6090** [comment]
是的，gpu预测会卡好长时间，结果为空（可能是我的电脑的事情
cpu预测一会就能出结果
谢谢！十分感谢！

**Comment by linlin6090** [comment]
这个数据集添加，我看文档里写的，说要纯中文，那要是想要做验证码那种英文咋办

**Comment by yeyupiaoling** [comment]
去PPASR那边，
你的数字是读英文的，还是读中文的

**Comment by linlin6090** [comment]
数字是中文的，字母是英文的，那种没有语义的识别，我在看ppasr，这个可以嘛

**Comment by yeyupiaoling** [comment]
可以的
