### ISSUE TITLE
你好  我想问一下训练的数据可以分批训练吗  数据量太大经常卡死

### ISSUE THREAD

**Issue by liangshu-code** [yeyupiaoling/PaddlePaddle-DeepSpeech#161]
我的电脑环境信息：
Paddle version: 2.1.3
Paddle With CUDA: True

OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: N/A
Libc version: glibc 2.31
Python version: 3.8.0

CUDA version: 11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
cuDNN version: N/A
Nvidia driver version: 535.54.03
Nvidia driver List: 
GPU 0: Quadro P5000

**Comment by liangshu-code** [comment]
![image](https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/assets/65603837/ff383613-90ce-4438-84a9-f69b3724dc86)

**Comment by liangshu-code** [comment]
![image](https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/assets/65603837/c9e58b9f-976a-40f4-bc11-0d51fd2e4e4a)

**Comment by yeyupiaoling** [comment]
分批不了，分批对训练不好。
