### ISSUE TITLE
仓库没有./dataset/zh_vocab.txt文件

### ISSUE THREAD

**Issue by wending0417** [yeyupiaoling/PaddlePaddle-DeepSpeech#162]
作者您好，为在本地进行快速预测，执行export_model.py的时候报错FileNotFoundError: [Errno 2] No such file or directory: './dataset/zh_vocab.txt'。repo里面并没有这个文件，请问应该如何解决？

**Comment by yeyupiaoling** [comment]
这个文件需要制作数据集的时候，或者下载模型的时候有的。
