### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by ZZz433** [yeyupiaoling/PaddlePaddle-DeepSpeech#164]
作者你好我运行脚本会出现
ModuleNotFoundError: No module named 'paddle.fluid'

**Comment by yeyupiaoling** [comment]
安装项目要求版本的 paddle&nbsp;

**Comment by ZZz433** [comment]
我已经安装了2.1.2，还是不行
![Uploading 2023-12-30 12-33-47屏幕截图.png…]()

**Comment by ZZz433** [comment]
![2023-12-30 12-33-47屏幕截图](https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/assets/118918908/44c36dfb-8769-499f-a833-5ef54e1aebbc)

**Comment by ZZz433** [comment]
已经解决上面的了 我想试用以下cpu报以下错误
![2023-12-30 13-03-21屏幕截图](https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/assets/118918908/2b9dc04c-b609-4e83-9728-d14610f73c42)

**Comment by yeyupiaoling** [comment]
我没试过使用CPU跑

**Comment by yeyupiaoling** [comment]
@FairyJi 用PPASR吧：https://github.com/yeyupiaoling/PPASR
