### ISSUE TITLE
关于模型预热

### ISSUE THREAD

**Issue by Nyannerso** [yeyupiaoling/PaddlePaddle-DeepSpeech#165]
大佬我看到predict.py里面init函数的倒数五行有一段预热的代码，这里的预热代码和infer_path.py里面的predict_audio里面的预测函数有什么区别吗？这里执行两次有什么效果，我把预热函数注释掉只会速度就很慢了。这里的预热函数有实际作用吗？主要是想做实时语音识别
<img width="325" alt="问题" src="https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/assets/133750284/af9e1473-5427-4bc7-a110-35f2afaa1663">

**Comment by yeyupiaoling** [comment]
因为第一次推理慢，所以要空跑一次

**Comment by Nyannerso** [comment]
> 因为第一次推理慢，所以要空跑一次

好的。那我做实时的语音识别时也只需要空跑一次吗？

**Comment by yeyupiaoling** [comment]
你不用也没事，就第一次比较慢而且

**Comment by yeyupiaoling** [comment]
这个不是流式实时模型，你可以看 ppasr&nbsp;

**Comment by Nyannerso** [comment]
> 这个不是流式实时模型，你可以看 ppasr&nbsp;

好的好的
