### ISSUE TITLE
运行本地预测没有输出

### ISSUE THREAD

**Issue by Xjorker** [yeyupiaoling/PaddlePaddle-DeepSpeech#167]
D:\anaconda\envs\py37\lib\site-packages\librosa\core\constantq.py:1058: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
-----------  Configuration Arguments -----------
alpha: 1.2
beam_size: 10
beta: 0.35
cutoff_prob: 1
cutoff_top_n: 40
decoding_method: ctc_greedy
enable_mkldnn: False
is_long_audio: False
lang_model_path: ./lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: ./dataset/mean_std.npz
model_dir: ./models/infer/
to_an: True
use_gpu: True
vocab_path: ./dataset/zh_vocab.txt
wav_path: ./dataset/test.wav
------------------------------------------------
我的环境是：
win11
cuda 10.2
cudnn7.6.5
paddlepaddle-gpu2.3.2
已经导出模型
请问本地预测为什么没有输出啊？

**Comment by Xjorker** [comment]
D:\anaconda\envs\py37\lib\site-packages\paddle\fluid\framework.py:6299: UserWarning: Skip loading for 'gru_5.b_0_beta2_pow_acc_0'. Because 'gru_5.b_0_beta2_pow_acc_0' not in the program.
  format(name)))
D:\anaconda\envs\py37\lib\site-packages\paddle\fluid\framework.py:6299: UserWarning: Skip loading for 'gru_5.w_0_moment1_0'. Because 'gru_5.w_0_moment1_0' not in the program.
  format(name)))
D:\anaconda\envs\py37\lib\site-packages\paddle\fluid\framework.py:6299: UserWarning: Skip loading for 'gru_5.w_0_moment2_0'. Because 'gru_5.w_0_moment2_0' not in the program.
  format(name)))
D:\anaconda\envs\py37\lib\site-packages\paddle\fluid\framework.py:6299: UserWarning: Skip loading for 'gru_5.w_0_beta1_pow_acc_0'. Because 'gru_5.w_0_beta1_pow_acc_0' not in the program.
  format(name)))
D:\anaconda\envs\py37\lib\site-packages\paddle\fluid\framework.py:6299: UserWarning: Skip loading for 'gru_5.w_0_beta2_pow_acc_0'. Because 'gru_5.w_0_beta2_pow_acc_0' not in the program.
  format(name)))
D:\anaconda\envs\py37\lib\site-packages\paddle\fluid\framework.py:6299: UserWarning: Skip loading for 'learning_rate_0'. Because 'learning_rate_0' not in the program. 
  format(name)))
[2024-04-21 11:34:40.411316] 成功加载模型：./models/param/50.pdparams
成功导出模型，模型保存在：./models/infer/
模型导出的时候也是有很多userwarning，感觉是模型导出有问题？

**Comment by yeyupiaoling** [comment]
警告不一定是错误，如果配置文件和加载的模型没有问题，一般不会有问题的。

**Comment by Xjorker** [comment]
> 警告不一定是错误，如果配置文件和加载的模型没有问题，一般不会有问题的。

你好，我用的是文档提供的数据集，但是预测没有输出

**Comment by yeyupiaoling** [comment]
有没有报什么错误或者输出的什么？

**Comment by Xjorker** [comment]
![image](https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/assets/71616073/506b6fb2-6d6c-4c53-8dfd-f081fa63c97e)

**Comment by Xjorker** [comment]
> 有没有报什么错误或者输出的什么？
![image](https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/assets/71616073/57321572-4c6b-4c09-8c46-40a833f2df3d)
这就是s输出了

**Comment by yeyupiaoling** [comment]
@Xjorker 那应该是你的模型没有训练好，
