### ISSUE TITLE
打不开本地部署的网页

### ISSUE THREAD

**Issue by tak7962** [yeyupiaoling/PaddlePaddle-DeepSpeech#168]
python infer_server.py后浏览器输入localhost:5000显示NOT FOUND,控制台里显示GET /HTTP/1.1 404-

**Comment by yeyupiaoling** [comment]
你的visualdl正常启动了吗？

**Comment by tak7962** [comment]
进行本地预测时也要运行visualdl吗，我是直接下载的模型们并没有试过在训练时打开visualdl

**Comment by yeyupiaoling** [comment]
不用，我以为你要用visualdl

**Comment by tak7962** [comment]
大佬，请问这个问题要怎么解决啊

**Comment by yeyupiaoling** [comment]
那个程序你启动了吗？你是本地启动的吗？如果不是的话，那个要改成你的ip地址才行。

**Comment by tak7962** [comment]
我是本地启动的,运行后他跳出来这些。
-----------  Configuration Arguments -----------
alpha: 1.2
beam_size: 300
beta: 0.35
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_greedy
enable_mkldnn: False
host: 0.0.0.0
lang_model_path: ./lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: ./dataset/mean_std.npz
model_dir: ./models/infer/
port: 5000
save_path: dataset/upload/
use_gpu: True
vocab_path: ./dataset/zh_vocab.txt
------------------------------------------------
 * Serving Flask app 'infer_server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.114:5000
 输入localhost:5000后显示NOT FOUND,The requested URL was not found on the server.

**Comment by tak7962** [comment]
你好，请问这要怎么解决

**Comment by yeyupiaoling** [comment]
日志上面有报什么错误吗？你直接点击这个ip地址进去，能不能访问？

**Comment by tak7962** [comment]
> 日志上面有报什么错误吗？你直接点击这个ip地址进去，能不能访问？

你好，我今天自己解决了，感谢
