### ISSUE TITLE
离线配置环境问题

### ISSUE THREAD

**Issue by guofengming11** [yeyupiaoling/PaddlePaddle-DeepSpeech#17]
请问公司的离线服务器无法直接运行decoder中的setup.sh，该怎么安装ctc_decoders
现在运行主程序报错是：
modulenotfounderror: no module named'ctc_decoders'
非常感谢！

**Comment by yeyupiaoling** [comment]
@guofengming11 看这个脚本：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/master/decoders/setup.sh

**Comment by yeyupiaoling** [comment]
@guofengming11 离线的服务器，前面的库你也安装不了？要不你做一个docker，复制过去看行不行

**Comment by guofengming11** [comment]
感谢开源 解决了
