### ISSUE TITLE
语音合成过程中缺少文件

### ISSUE THREAD

**Issue by Drewwuyuyang** [yeyupiaoling/PaddlePaddle-DeepSpeech#174]
你好 github上的工程文件中没有这个models的文件也找不到fastspeech2_nosil_aishell3_ckpt_0.4这个文件夹
![屏幕截图 2024-07-05 132210](https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/assets/107189850/b71bf1b5-6b1e-4cfa-b413-fb91e1e519ce)

**Comment by yeyupiaoling** [comment]
这个是额外下载的
