### ISSUE TITLE
export FLAGS_sync_nccl_allreduce=0的意义

### ISSUE THREAD

**Issue by guofengming11** [yeyupiaoling/PaddlePaddle-DeepSpeech#20]
export FLAGS_sync_nccl_allreduce=0
这行代码是训练前先在命令行里执行么？ 意义是什么呢？

**Comment by yeyupiaoling** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/flags/others_cn.html#flags-sync-nccl-allreduce

**Comment by yeyupiaoling** [comment]
@guofengming11 你不执行也可以的

**Comment by yeyupiaoling** [comment]
@guofengming11 就一个加速的策略

**Comment by guofengming11** [comment]
好的 多谢了
