### ISSUE TITLE
运行sudo sh setup.sh错误

### ISSUE THREAD

**Issue by 245789064** [yeyupiaoling/PaddlePaddle-DeepSpeech#22]
Running setup.py install for llvmlite ... error

RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
求大神指点这个错误应该怎么解决。
是不是要安装LLVM这个工具啊

**Comment by yeyupiaoling** [comment]
@245789064 这个是安装numba时用到的，可以单独安装，具体版本看下面，如何出现llvmlite无法卸载，可以直接删除这个文件，具体路径他会提示的。
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/f8dde7f45b1f3666c42e23bbec3f46d40e6e39d5/setup.sh#L19

**Comment by 245789064** [comment]
大神，我在setup.sh文件中删掉了numba==0.52.0，为啥还是会运行 llvmlite的安装啊

**Comment by yeyupiaoling** [comment]
你手动安装一下llvmlite

**Comment by zhangyifei1** [comment]
> 大神，我在setup.sh文件中删掉了numba==0.52.0，为啥还是会运行 llvmlite的安装啊

你是在docker里面安装的吗？

**Comment by yeyupiaoling** [comment]
我是本地使用的，安装过程很顺利。

**Comment by zhangyifei1** [comment]
> 我是本地使用的，安装过程很顺利。

我本地安装，有个swig_decoders 模块，愁死了，怎么也安装不上，折磨我好几天了

**Comment by zhangyifei1** [comment]
> 我是本地使用的，安装过程很顺利。

在网上查，说是要安装swig   0.3.1版本。我安装过了，还是装不上swig_decoders

**Comment by yeyupiaoling** [comment]
swig_decoders 这个最大的问题是git clone源码的时候会失败，导致没有下载依赖源码。你看一下是不是这个原因。

**Comment by yeyupiaoling** [comment]
你截取全部的错误给我看一下

**Comment by yeyupiaoling** [comment]
@zhangyifei1 麻烦给个star

**Comment by 245789064** [comment]
我都忘记给星了，赶紧上来给星，大神NB!

**Comment by zhangyifei1** [comment]
> 你截取全部的错误给我看一下

执行sh run_train.sh的时候报这个。
![image](https://user-images.githubusercontent.com/28425091/112409311-3de32e00-8d54-11eb-966c-d1e3ca158f30.png)
cd 到decoders/swig 目录下，sh setep.sh手动安装swig_decoders   出来一大堆这些东西。。。
![image](https://user-images.githubusercontent.com/28425091/112409482-8c90c800-8d54-11eb-9ea5-39e0df95df40.png)

最后安装完，pip3  list 还是没有swig_decoders这个包

**Comment by zhangyifei1** [comment]
> @zhangyifei1 麻烦给个star

已经star

**Comment by yeyupiaoling** [comment]
@zhangyifei1 你用的不是我的项目啊。你这个编译过程还是正确的，要看最后的错误情况。警告的不用管。

**Comment by zhangyifei1** [comment]
> @zhangyifei1 你用的不是我的项目啊。你这个编译过程还是正确的，要看最后的错误情况。警告的不用管。

我用的是官网的1.85分支，最后显示这个，就不动了。
![image](https://user-images.githubusercontent.com/28425091/112409938-5273f600-8d55-11eb-9af1-06088e872dd9.png)

点了回车后，就回到了ubuntu的操作命令行了。pip3 list也没有swig_decoders这个包

大神，方便加个v么。z15638125431

**Comment by yeyupiaoling** [comment]
@zhangyifei1 不动是因为还在编译，需要时间的，等。上面编译的就是这个swig_decoders。我的跟官方的有所不同，不能通用的。

**Comment by zhangyifei1** [comment]
> @zhangyifei1 不动是因为还在编译，需要时间的，等。上面编译的就是这个swig_decoders。我的跟官方的有所不同，不能通用的。

我一会用您的这个项目试一下，很苦恼，官方的docker环境更乱，

**Comment by zhangyifei1** [comment]
> @zhangyifei1 不动是因为还在编译，需要时间的，等。上面编译的就是这个swig_decoders。我的跟官方的有所不同，不能通用的。

大神，这个错误是什么意思，麻烦有空的时候可以帮忙看一眼吗？嘿嘿，，，
![image](https://user-images.githubusercontent.com/28425091/112563092-a513e780-8e13-11eb-8da5-0dfbcfa8e3b6.png)

**Comment by yeyupiaoling** [comment]
这个我没遇到过，看一下依赖环境都安装了没。
