### ISSUE TITLE
 将ctc_decoders单独出来编译

### ISSUE THREAD

**Issue by 245789064** [yeyupiaoling/PaddlePaddle-DeepSpeech#23]
将ctc_decoders单独出来编译   是指在decoder文件夹下运行setup.sh文件吗

**Comment by 245789064** [comment]
我是这个问题:ModuleNotFoundError: No module named 'ctc_decoders'

**Comment by 245789064** [comment]
尝试将在decoder文件夹下运行setup.sh文件之后，没有解决问题，谢谢大神有时间指导下

**Comment by yeyupiaoling** [comment]
@245789064 执行根目录下的setup.sh，他会自动执行decoder中的setup.sh，如果安装不成功，多数是git clone拉取文件失败。
