### ISSUE TITLE
多卡速度问题

### ISSUE THREAD

**Issue by deepsmallsea033** [yeyupiaoling/PaddlePaddle-DeepSpeech#25]
您好，我在训练过程中发现，一个batch,用两块儿卡比一块卡还要慢。单卡跑一个batch 要3分钟，双卡跑一个batch用了8分钟。

**Comment by yeyupiaoling** [comment]
@deepsmallsea033 你看一下GPU的使用率？如果使用率太低，可能是数据读取速度跟不上。
