### ISSUE TITLE
声道数、采样率、模型

### ISSUE THREAD

**Issue by guofengming11-chinese** [yeyupiaoling/PaddlePaddle-DeepSpeech#26]
1、请问作者声道数和采样率对识别结果影响大吗，它们分别是多少的时候识别效果最好呢？
2、作者还有用更大的数据集训练出来的模型么？现在的这几个发布的模型感觉在实际的对话录音场景中，效果还是不够理想额。。。
非常感谢

**Comment by yeyupiaoling** [comment]
声道数和采样率 在训练之前都统一转为单通道，16000Hz的。
那个1300小时的数据已经很大了。
