### ISSUE TITLE
超大规模预训练模型和官方的vocab不匹配。

### ISSUE THREAD

**Issue by njuptpz** [yeyupiaoling/PaddlePaddle-DeepSpeech#3]
你好，官方的vocab和mean_std和这个预训练不匹配，能不能提供预制配套的vocab和mean_std

**Comment by yeyupiaoling** [comment]
@njuptpz 已经提供了，你看一下，都正在`step_final`目录中，

**Comment by yeyupiaoling** [comment]
@njuptpz 我重新修改目录，分享了：https://share.weiyun.com/augQttoq
