### ISSUE TITLE
无法打开麦克风。异常信息:18

### ISSUE THREAD

**Issue by zhangyifei1** [yeyupiaoling/PaddlePaddle-DeepSpeech#30]
访问localhost:5002  ，点击录音按钮会报错：无法打开麦克风。异常信息:18。请问是什么原因？

**Comment by yeyupiaoling** [comment]
你看看是不是没授权

**Comment by yeyupiaoling** [comment]
你看看是不是没授权

**Comment by zhangyifei1** [comment]
> 你看看是不是没授权

大佬你用的是https么，好像navigator.getUserMedia这个函数在新版浏览器要用https才可以

**Comment by yeyupiaoling** [comment]
@zhangyifei1 localhost 和 HTTPS 都可以的。

**Comment by zhangyifei1** [comment]
> @zhangyifei1 localhost 和 HTTPS 都可以的。

localhost是宿主机ubuntu系统，在局域网其他电脑访问不了

**Comment by yeyupiaoling** [comment]
你看下我最新代码的处理方式，
服务器接口：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/master/infer_server.py
客户端：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/master/client.py

文档：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech#%E8%AF%84%E4%BC%B0%E5%92%8C%E9%A2%84%E6%B5%8B
