### ISSUE TITLE
ctc_decoder安装问题

### ISSUE THREAD

**Issue by ilove-Moretz** [yeyupiaoling/PaddlePaddle-DeepSpeech#31]
![图片](https://user-images.githubusercontent.com/22176146/114835059-c5780600-9e03-11eb-8d38-9c1debd03a87.png)

**Comment by yeyupiaoling** [comment]
这个不是安装成功了吗？

**Comment by ilove-Moretz** [comment]
> 
> 
> 这个不是安装成功了吗？

但是运行会出现下图的问题
![图片](https://user-images.githubusercontent.com/22176146/114841147-1be84300-9e0a-11eb-83b0-1bf909e2a9ea.png)
我的python虚拟环境的路径的路径是“/anaconda3/envs/wbq_paddle/lib/python3.7”，图片中显示安装到了/usr/local/lib/python3.5/dist-packages

**Comment by MY-stone** [comment]
我执行安装程序后运行代码出现 no moddle ctc_decoder，我想问一下是缺少了哪个依赖。
```
  File "infer_path.py", line 6, in <module>   
    from model_utils.model import DeepSpeech2Model   
  File "/data-tmp/PaddlePaddle-DeepSpeech/model_utils/model.py", line 14, in <module>   
    from ctc_decoders.swig_wrapper import Scorer   
ModuleNotFoundError: No module named 'ctc_decoders'
```

**Comment by yeyupiaoling** [comment]
进入到decoders重新执行setup.sh就好
