### ISSUE TITLE
想拿作者训练好的模型只跑测试，可以不用装docker吗，需要安装哪些依赖库？

### ISSUE THREAD

**Issue by yxy-lol** [yeyupiaoling/PaddlePaddle-DeepSpeech#32]
想作为一个工具来识别音频输出文本

**Comment by yeyupiaoling** [comment]
你看文档，默认就不使用docker，在本地跑，同样要执行`setup.sh`安装全部的依赖环境。

**Comment by yxy-lol** [comment]
> 你看文档，默认就不使用docker，在本地跑，同样要执行`setup.sh`安装全部的依赖环境。

谢谢，测试跑通了，打算再找个英文的预训练模型
