### ISSUE TITLE
可以在windows上训练吗？

### ISSUE THREAD

**Issue by wingdi** [yeyupiaoling/PaddlePaddle-DeepSpeech#33]
windows可以装ubuntu，但是navidia-docker使用不了

**Comment by yeyupiaoling** [comment]
不可以，就算在Windows安装了Ubuntn。没有无法使用显卡也是不行的

**Comment by wingdi** [comment]
> 不可以，就算在Windows安装了Ubuntn。没有无法使用显卡也是不行的

好的，多谢
