### ISSUE TITLE
dataloader能不能多进程加载数据啊

### ISSUE THREAD

**Issue by 0we** [yeyupiaoling/PaddlePaddle-DeepSpeech#34]
能像PPASR一样加num_worker多进程加载data吗

**Comment by yeyupiaoling** [comment]
不想，这个是用旧版本PaddlePaddle实现的，跟PPASR不同。

**Comment by 0we** [comment]
> 不想，这个是用旧版本PaddlePaddle实现的，跟PPASR不同。

哦难怪多卡多内存也训练效率不高，PPASR却跑的飞快

**Comment by yeyupiaoling** [comment]
@0we PPASR却跑的飞快 有两个原因，另外一个是目前PPASR使用的是小模型，训练很快。
