### ISSUE TITLE
关于预测接口问题

### ISSUE THREAD

**Issue by deepsmallsea033** [yeyupiaoling/PaddlePaddle-DeepSpeech#36]
您好，
1.输入的音频数据都需要转成wav后才能喂到接口里吗？目前接口支持哪个格式的语音数据
2.接口有没有转换采样频率的逻辑，还是说必须调整好采用频率后才能给到接口里
谢谢

**Comment by yeyupiaoling** [comment]
是的，目前支持wav格式。其他的应该也支持，当时我没试过，用的是Soundfile读取的，这个支持，那就支持，但是一些压缩的因为最好不用，例如mp3格式。要使用无压缩的，例如wav、pcm

采样率会自动转换的。

**Comment by FrankWhh** [comment]
> 是的，目前支持wav格式。其他的应该也支持，当时我没试过，用的是Soundfile读取的，这个支持，那就支持，但是一些压缩的因为最好不用，例如mp3格式。要使用无压缩的，例如wav、pcm
> 
> 采样率会自动转换的。

您好！我看那个自搜集数据集都是MP3 格式，训练的时候都需要先转换成WAV格式？

**Comment by FrankWhh** [comment]
导入的python Wave模块只能解析WAV格式的音频文件

**Comment by yeyupiaoling** [comment]
@FrankWhh 使用librosa转换一下吧

**Comment by FrankWhh** [comment]
> @FrankWhh 使用librosa转换一下吧

谢谢 我用pydub转了
