### ISSUE TITLE
document so large,else ways to pull container

### ISSUE THREAD

**Issue by 5859wang** [yeyupiaoling/PaddlePaddle-DeepSpeech#4]
docker pull is so large have else  to download docker container?

**Comment by yeyupiaoling** [comment]
@5859wang You can install the environment locally. Because CUDA and other environments are included in Docker, it is normal for Docker to be relatively large.

**Comment by yeyupiaoling** [comment]
@5859wang Hi, I will close this issue if there is no problem.
