### ISSUE TITLE
大佬，加载自己之前的预训练模型报错怎么办呢？

### ISSUE THREAD

**Issue by YY007H** [yeyupiaoling/PaddlePaddle-DeepSpeech#40]
![图片](https://user-images.githubusercontent.com/15188456/118924929-64969d00-b970-11eb-8ddd-5dc25920de76.png)
![图片](https://user-images.githubusercontent.com/15188456/118924921-5e082580-b970-11eb-98d2-94a81a3bc562.png)

**Comment by yeyupiaoling** [comment]
@YY007H 类别数量不对吧？

**Comment by YY007H** [comment]
就直接拿刚训练过的模型，再进行预加载也报错

**Comment by yeyupiaoling** [comment]
@YY007H 那不应该啊，网络结构都对不上了。

**Comment by YY007H** [comment]
我从新获取了最新的代码，还是不行，预训练模型也能正常预测，就是训练的时候不能正常加载

**Comment by yeyupiaoling** [comment]
你直接加载自己刚训练的模型也不行吗？你其他参数都不要改动。

**Comment by YY007H** [comment]
嗯嗯，是的

**Comment by yeyupiaoling** [comment]
@YY007H 你的PaddlePaddle是1.8.5吗？如果不加载模型可以正常训练？

**Comment by YY007H** [comment]
嗯嗯，不加载模型可以正常训练

**Comment by yeyupiaoling** [comment]
让我看看的你参数配置

**Comment by YY007H** [comment]
![图片](https://user-images.githubusercontent.com/15188456/118935035-a67a1000-b97d-11eb-8928-86abd411c07f.png)

**Comment by YY007H** [comment]
我好方，把代码重新拉取了一遍，重新编译重新跑，可以加载我训练的预训练模型了
不过之前训练的模型还是不能加载，但是在新的编译代码上能正常进行预测

**Comment by yeyupiaoling** [comment]
@YY007H 你肯定是改了模型代码，你试试使用新的代码训练一个模型，加载试试

**Comment by yeyupiaoling** [comment]
预测的program和测试的program有点不一样

**Comment by YY007H** [comment]
大佬有没有可以用的预训练模型，重新训练需要一周的时间

**Comment by yeyupiaoling** [comment]
你认真看完我的文档好吧

**Comment by YY007H** [comment]
多谢多谢，有段时间没看文档了，还以为没有呢
