### ISSUE TITLE
用/models/step_final/做预训练模型报错。

### ISSUE THREAD

**Issue by zhangyifei1** [yeyupiaoling/PaddlePaddle-DeepSpeech#41]
![image](https://user-images.githubusercontent.com/28425091/120415340-f39eae80-c38d-11eb-915b-a888bd050a11.png)

**Comment by yeyupiaoling** [comment]
@zhangyifei1 模型输入大小不对，你得用配套的数据字典

**Comment by zhangyifei1** [comment]
> @zhangyifei1 模型输入大小不对，你得用配套的数据字典

我用的是您贴的训练好的数据集，请问您有对应的字典吗？

**Comment by zhangyifei1** [comment]
> @zhangyifei1 模型输入大小不对，你得用配套的数据字典

我用的是您贴的训练好的模型，请问您有对应的字典吗？

**Comment by yeyupiaoling** [comment]
你下载模型的文件就有数据集字典，在dataset目录下

**Comment by zhangyifei1** [comment]
> 你下载模型的文件就有数据集字典，在dataset目录下

dataset目录的字典是6486行的，模型是不是需要一个4869行的字典呀？请问这个有办法获取吗？

**Comment by yeyupiaoling** [comment]
你下载的是哪个模型？

**Comment by zhangyifei1** [comment]
> 你下载的是哪个模型？

![image](https://user-images.githubusercontent.com/28425091/120416397-a8859b00-c38f-11eb-8c68-bf4a0af0ce52.png)
大佬，我下载的是这个。

**Comment by yeyupiaoling** [comment]
不应该的，我这个模型就是6486输出的，你看一下是不是加载错模型了

**Comment by zhangyifei1** [comment]
> 不应该的，我这个模型就是6486输出的，你看一下是不是加载错模型了

![image](https://user-images.githubusercontent.com/28425091/120416698-25187980-c390-11eb-84b4-103e5bcda8c5.png)
应该没错的，837M的模型。

**Comment by zhangyifei1** [comment]
> > 不应该的，我这个模型就是6486输出的，你看一下是不是加载错模型了
> 
> ![image](https://user-images.githubusercontent.com/28425091/120416698-25187980-c390-11eb-84b4-103e5bcda8c5.png)
> 应该没错的，837M的模型。

![Uploading image.png…]()

**Comment by yeyupiaoling** [comment]
@zhangyifei1 我刚才是过了，没有问题的，应该是你下载错误了，或者加载错误的模型、

**Comment by zhangyifei1** [comment]
> @zhangyifei1 我刚才是过了，没有问题的，应该是你下载错误了，或者加载错误的模型、

![image](https://user-images.githubusercontent.com/28425091/120418799-c523d200-c393-11eb-9278-c2ee550d0dec.png)
我是通过这个渠道，4.9号下载的，不是这个模型吗？

**Comment by yeyupiaoling** [comment]
那你看看是不是解压到其他地方了，因为其他模型的名字也是一样的。

**Comment by zhangyifei1** [comment]
大神。我有新的数据集，能否不做zh_vocab，直接用step_final的zh_vocab？
因为如果做了zh_vocab会导致字符集大小不一致而报错。

**Comment by yeyupiaoling** [comment]
可以的，那个字典已经包含了足够多的字符了。
