### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './dataset/mean_std.npz'

### ISSUE THREAD

**Issue by guochongjun** [yeyupiaoling/PaddlePaddle-DeepSpeech#42]
作用python3 eval.py --model_path=./models/step_final/报错,FileNotFoundError: [Errno 2] No such file or directory: './dataset/mean_std.npz'

**Comment by yeyupiaoling** [comment]
@guochongjun 你将下载的模型文件中的mean_std.npz放在dataset目录下

**Comment by guochongjun** [comment]
链接发下不

**Comment by yeyupiaoling** [comment]
@guochongjun 看文档

**Comment by guochongjun** [comment]
FileNotFoundError: [Errno 2] No such file or directory: './dataset/manifest.test'

**Comment by yeyupiaoling** [comment]
@guochongjun 这个是数据集的列表，你没有数据集就不能评估数据集的准确率。你直接预测音频就好。
