### ISSUE TITLE
ValueError: Failed to parse the augmentation config json: [Errno 2] No such file or directory: 'dataset/manifest.noise'

### ISSUE THREAD

**Issue by guochongjun** [yeyupiaoling/PaddlePaddle-DeepSpeech#44]
ValueError: Failed to parse the augmentation config json: [Errno 2] No such file or directory: 'dataset/manifest.noise'这个怎么搞

**Comment by yeyupiaoling** [comment]
@guochongjun 如果你没有噪声数据，可以删除这些代码：
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/90f61fa3a4d8acdb11f1cbe3dc614423f60ce570/conf/augmentation.config#L2-L8

可以看这个文档了解：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech#%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA
