### ISSUE TITLE
infer_path

### ISSUE THREAD

**Issue by Andrew-Zhang98** [yeyupiaoling/PaddlePaddle-DeepSpeech#45]
您好，我想直接用你提供的模型对我的音频进行ASR预测(https://deepspeech.bj.bcebos.com/zh_lm/zh_giga.no_cna_cmn.prune01244.klm)
那么我应该使用那个数据集对应的mean_std.npz和zh_vocab.txt呢。
请问您是否有已经处理好的这两个文件，如果可以希望可以共享一下。358607757@qq.com

**Comment by yeyupiaoling** [comment]
@Andrew-Zhang98 你下载模型压缩包中，已经包含了这两个文件的。

**Comment by Andrew-Zhang98** [comment]
'zh_giga.no_cna_cmn.prune01244.klm' 请问您指的是这个文件嘛，我要怎样解压呢

**Comment by yeyupiaoling** [comment]
@Andrew-Zhang98 这个是语音模型，不用解压的
模型和其他相关文件在这下载：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech#%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD
