### ISSUE TITLE
win10可以运行吗？

### ISSUE THREAD

**Issue by Yang-Changhui** [yeyupiaoling/PaddlePaddle-DeepSpeech#46]
我想请问win10可以运行吗，ModuleNotFoundError: No module named 'swig_decoders'，我运行的时候这个包安装不上

**Comment by yeyupiaoling** [comment]
@Yang-Changhui 不可以的，这个只能在Linux下编译，如果先再windows使用语音识别，用这个项目：https://github.com/yeyupiaoling/PPASR

**Comment by Yang-Changhui** [comment]
好的，谢谢

**Comment by Yang-Changhui** [comment]
请问一下，你给我发的这个项目里，vocabulary.json怎么下载

**Comment by yeyupiaoling** [comment]
执行这个代码自动生成的

![微信截图_20210713143516](https://user-images.githubusercontent.com/26297768/125402984-944da880-e3e7-11eb-9f31-65c2d6a16832.png)

**Comment by Yang-Changhui** [comment]
好的，谢谢啦，实在不好意思啊，打扰你了

**Comment by yeyupiaoling** [comment]
最新代码可以进行windows了
