### ISSUE TITLE
模型加载问题

### ISSUE THREAD

**Issue by 274349293** [yeyupiaoling/PaddlePaddle-DeepSpeech#47]
![image](https://user-images.githubusercontent.com/48706958/125403703-6321a800-e3e8-11eb-8e49-856a1aa332eb.png)
如图，卡在这一步

**Comment by yeyupiaoling** [comment]
@274349293 你用的是GPU推理吗？卡多久了？

**Comment by 274349293** [comment]
> @274349293你用的是GPU推理吗？卡会了吗？

是GPU，一直不动，等很久了，不确定是哪里出问题了

**Comment by yeyupiaoling** [comment]
@274349293 你打印这个结果看看，看有没有结果输出。
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/906eea72363ffff85d0278ee276835f92ab4ed38/infer_path.py#L62

**Comment by 274349293** [comment]
> @274349293 你打印这个结果看看，看有没有结果输出。
> https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/906eea72363ffff85d0278ee276835f92ab4ed38/infer_path.py#L62

无法打印，打印结果只能到data_generator这一步，ds2_model(43行)之后无法打印，请问是什么问题

**Comment by yeyupiaoling** [comment]
好像没有加载模型成功，你的模型路径正确吗？
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/906eea72363ffff85d0278ee276835f92ab4ed38/model_utils/model.py#L164

**Comment by 274349293** [comment]
> 你指定的文件中应该有`params.pdparams`这个文件的。![image](https://user-images.githubusercontent.com/48706958/125406730-bd703800-e3eb-11eb-94be-2e4d82c21254.png)
这是我的模型路径

**Comment by yeyupiaoling** [comment]
这应该是没有问题的。你的PaddlePaddle版本是1.8.5吗？

**Comment by yeyupiaoling** [comment]
这应该是没有问题的。你的PaddlePaddle版本是1.8.5吗？

**Comment by 274349293** [comment]
> 这应该是没有问题的。你的PaddlePaddle版本是1.8.5吗？

是的，docker环境完全是按照install做的，安装的是PaddlePaddle 1.8.5.post107的GPU版本

**Comment by yeyupiaoling** [comment]
不应该啊，你的GPU是什么。显存多少？

**Comment by 274349293** [comment]
> 不应该啊，你的GPU是什么。显存多少？

3090 24G ,显存应该是够用的 😭

**Comment by yeyupiaoling** [comment]
3090 不是不支持CUDA10吗

**Comment by 274349293** [comment]
> 3090 不是不支持CUDA10吗

哦哦，是这样的吗 ，我换一张2080ti试一下

**Comment by 274349293** [comment]
> 3090 不是不支持CUDA10吗

![image](https://user-images.githubusercontent.com/48706958/125409588-9cf5ad00-e3ee-11eb-85a4-d8cc762ba1ab.png)
我换了2080ti  但是问题好像并不是出在了这里

**Comment by yeyupiaoling** [comment]
看下这个文件 的路径：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/906eea72363ffff85d0278ee276835f92ab4ed38/infer_path.py#L23

**Comment by yeyupiaoling** [comment]
我看你是放在models/step_final目录下的

**Comment by 274349293** [comment]
> 看下这个文件 的路径：![image](https://user-images.githubusercontent.com/48706958/125410126-2b6a2e80-e3ef-11eb-9754-89f67e9d04cc.png)> 
> https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/906eea72363ffff85d0278ee276835f92ab4ed38/infer_path.py#L23

这些我都已经放好了，是按照infer_path.py里面的参数默认路径放的

**Comment by yeyupiaoling** [comment]
尝试不使用GPU看看。
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/906eea72363ffff85d0278ee276835f92ab4ed38/infer_path.py#L21

**Comment by 274349293** [comment]
> 尝试不使用GPU看看。
> https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/906eea72363ffff85d0278ee276835f92ab4ed38/infer_path.py#L21

不使用GPU是可以的运行的

**Comment by yeyupiaoling** [comment]
那应该是本身显卡的原因了，你本地安装的显卡驱动版本的原因吧、。

**Comment by 274349293** [comment]
> 那应该是本身显卡的原因了，你本地安装的显卡驱动版本的原因吧、。

非常感谢您的耐心解答！
