### ISSUE TITLE
使用gpu推理错误

### ISSUE THREAD

**Issue by Yang-Changhui** [yeyupiaoling/PaddlePaddle-DeepSpeech#49]
版本、环境信息：
   1）PaddlePaddle版本：Paddlepaddle2.0.2-gpu（直接安装官方编译好的whl）
   2）系统环境：NVIDIA Jetson AGX Xavier JetPack4.3 Ubuntu18.04、Python3.6.9,cuda10.0,cudnn7.6,
你好，当我将'use_gpu', 设为True的时候会出现如下错误
![捕获](https://user-images.githubusercontent.com/71805205/125744742-72143bb8-f59e-4236-90b5-9e8e19beb490.JPG)
将其改为False可以正常运行，只是时间会慢很多，
您是否遇到过这样的问题？

**Comment by yeyupiaoling** [comment]
这个应该是PaddlePaddle内部的问题，而且你用CPU推理正常，那程序应该是没有问题的。

**Comment by yeyupiaoling** [comment]
我建议你编译1.8.5版本的试一下。我这边全部都是用1.8.5的

**Comment by yeyupiaoling** [comment]
https://github.com/yeyupiaoling/PPASR
试试这个的入门级，

**Comment by Yang-Changhui** [comment]
这个PPASR在window上试过了，识别效果不是很好；用PaddlePaddle-DeepSpeech的话识别效果还是挺好的。
因为paddle1.8.5官方没有给出适合jetson agx xavier的版本，只有2.0.2以上支持；我自己用1.8.5编译了一下，但出错了，所以就用2.0.2试了一下；
还是非常感谢你

**Comment by yeyupiaoling** [comment]
哦哦，他们没有提供最新2.1.1版本的whl吗？你指改了代码吧，我的代码默认是不支持动态图的，2.0版本以上要开静态图模式

**Comment by Yang-Changhui** [comment]
对的，jetson agx xavier是linux_aarch64版本的whl；我改了model.py，使其只支持静态图

**Comment by yeyupiaoling** [comment]
哦哦

**Comment by yeyupiaoling** [comment]
@Yang-Changhui 你说的一样是什么意思？模型肯定是同一个模型，就是训练的数据集不一样，分别是这两个数据集AISHELL和thchs30。

**Comment by Yang-Changhui** [comment]
@yeyupiaoling 我看模型大小都是一样的，可能我把一个下了两次吧，你那个自收集的模型效果会更好吗

**Comment by yeyupiaoling** [comment]
@Yang-Changhui 看数据词汇表就知道了。
当然，AISHELL才100多小时，thchs30才几十小时，都不是一个数量级的。

**Comment by Yang-Changhui** [comment]
嗯呢，好的，谢谢

**Comment by zzzzyq-18** [comment]
> 这个PPASR在window上试过了，识别效果不是很好；用PaddlePaddle-DeepSpeech的话识别效果还是挺好的。
> 因为paddle1.8.5官方没有给出适合jetson agx xavier的版本，只有2.0.2以上支持；我自己用1.8.5编译了一下，但出错了，所以就用2.0.2试了一下；
> 还是非常感谢你

请问您的这个bug是怎么解决的呢

**Comment by zzzzyq-18** [comment]
> 我建议你编译1.8.5版本的试一下。我这边全部都是用1.8.5的

请问是把paddle换成1.8.5么，这样会有其他错误，没有inferrence，我现在也是改成True不行，False使用CPU就行

**Comment by yeyupiaoling** [comment]
@zzzzyq-18 你看这个文档：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech#nvidia-jetson%E9%A2%84%E6%B5%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA
