### ISSUE TITLE
超参数设置问题

### ISSUE THREAD

**Issue by NextGuido** [yeyupiaoling/PaddlePaddle-DeepSpeech#5]
@yeyupiaoling 你好，我在跑您的代码，数据集采用的是"MAGICDATA Mandarin Chinese Read Speech Corpus"，训练集大概有570000条语音。我的机器是单机RTX2080Ti，我的batch_size设为16，请问如何设置对应的学习率呢，训练太慢了，没法自己去一点点调参。感谢

**Comment by yeyupiaoling** [comment]
@NextGuido 学习率可以不用改，直接训练就好

**Comment by yeyupiaoling** [comment]
@NextGuido 你好，如果没有问题我就关闭这个issue了，有问题在提问。
