### ISSUE TITLE
AISHELL模型和1300小时模型对比

### ISSUE THREAD

**Issue by Yang-Changhui** [yeyupiaoling/PaddlePaddle-DeepSpeech#51]
你好，我下载了AISHELL模型和1300小时模型这两个模型，我下载了一段普通话片段，AISHELL模型效果会更好；如果是data_thchs30里面的数据集，是1300小时的模型更好一点，请问，你测试的时候也是这样吗

**Comment by yeyupiaoling** [comment]
你的音频哪里下载的？

**Comment by Yang-Changhui** [comment]
普通话学习网，《白杨礼赞》，http://www.pthxx.com/

**Comment by yeyupiaoling** [comment]
那不应该，1300小时应该会好一些，你对比更多的数据试试

**Comment by Yang-Changhui** [comment]
我试过不少，如果是哪几个公开数据集的音频的话，1300小时的会好很多，但是我下载别的音频的话相对来说AISHELL模型会会好很多
