### ISSUE TITLE
install error in docker

### ISSUE THREAD

**Issue by zdyupup** [yeyupiaoling/PaddlePaddle-DeepSpeech#53]
docker环境下运行sh setup.sh，最后信息如下：
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
Install all dependencies successfully.

根目录运行CUDA_VISIBLE_DEVICES=0,1 python3 train.py，报错信息为：
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from model_utils.model import DeepSpeech2Model
  File "/DeepSpeech/model_utils/model.py", line 14, in <module>
    from ctc_decoders.swig_wrapper import Scorer
ModuleNotFoundError: No module named 'ctc_decoders'

请问是编译未完成的问题吗？应该如何解决？

**Comment by yeyupiaoling** [comment]
你还没有安装ctc_decoders，你先重新安装
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/906eea72363ffff85d0278ee276835f92ab4ed38/setup.sh#L10

然后在执行这个两行命令
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/906eea72363ffff85d0278ee276835f92ab4ed38/setup.sh#L44-L45

**Comment by zdyupup** [comment]
是我设置远程连接之后，不小心重构了一些代码，重新git clone就可以了，感谢
