### ISSUE TITLE
下载小型模型测试使用问题

### ISSUE THREAD

**Issue by laitianan** [yeyupiaoling/PaddlePaddle-DeepSpeech#54]
根据readme，执行操作
mkdir lm
cd lm
wget https://deepspeech.bj.bcebos.com/zh_lm/zh_giga.no_cna_cmn.prune01244.klm
下载完毕小模型，之后进行推断测试，
执行：
python3 eval.py --model_path=./models/step_final/
出现错误：
 raise Warning("The pretrained params do not exist.")
查看代码，model_path参数中的训练保存的模型文件夹路径./models/step_final/没有，应该怎么办呢
能否提供一个完整的可执行的小型模型吗

**Comment by yeyupiaoling** [comment]
在文档最后提供下载了

**Comment by laitianan** [comment]
如果需要把一个小时的语音切割成最长不超过16秒子语音，请问有什么样的解决方案吗

**Comment by yeyupiaoling** [comment]
用VAD分割音频

**Comment by yeyupiaoling** [comment]
@laitianan 最近代码直接支持长语音识别了
