### ISSUE TITLE
识别很不准

### ISSUE THREAD

**Issue by wl-junlin** [yeyupiaoling/PaddlePaddle-DeepSpeech#55]
我下载了1300的那个model，test测试没问题 ==> 近几年不但我用输给女儿压岁也劝说亲朋不要给女儿压岁钱而改送压岁书

但是网上找了个音频，https://www.youtube.com/watch?v=oVi5EGbZy1A 
ctc_beam_search ==> 鹗狎狎狎狎槎棹狎棹只狎狎棹棹棹棹棹棹棹棹槎棹碴碴碴碴碴狎棹棹棹棹狎狎棹碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴他狎碴碴碴碴碴碴碴碴碴碴碴狎碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴他棹狎狎棹嵌狎狎碴碴碴碴碴碴他棹棹碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴碴狎棹棹他狎法狎膨棹碴碴碴碴碴碴起鳄嗅狎狎狎狎膨膨膨膨狎斡狎狎嵌灌溉起早家膨咱茬茬等你不住狎大贯膨实膨狎自前存找他的全藻但你膨膨膨茬茬膨下洒膨膨锻练但我就讲大攒攒攒钱攒攒攒攒趸
ctc_greedy ==> 棹狎狎狎狎狎辔狎狎槎狎棹狎棹狎槎呎棹狎棹洮狎槎槎棹狎狎棹棹狎棹狎棹狎棹棹棹棹棹棹棹棹槎棹棹棹棹棹棹棹狎棹棹棹棹棹棹狎棹狎唗棹棹狎狎棹棹呎槎狎棹鸠棹棹棹棹棹狎狎狎狎棹狎棹狎棹棹狎狎棹狎狎槎狎棹棹棹棹娑狎狎棹棹棹棹辔槎棹狎狎棹狎槎棹他碴禩狎棹狎狎狎棹棹棹狎棹狎狎棹狎辔棹棹棹棹棹棹狎狎狎狎狎呎槎辔棹狎嵌棹棹狎棹棹狎狎狎狎棹狎棹狎棹狎棹棹斡棹狎狎狎棹狎棹狎棹狎讲棹棹狎棹狎狎狎棹狎狎狎棹狎狎棹趔棹槎棹棹棹棹狎狎棹棹棹棹棹棹棹棹棹棹棹棹棹棹棹棹棹棹棹狎棹棹棹棹棹棹棹狎狎狎棹棹他狎棹法狎嗪棹棹棹狎茬棹棹棹棹起狎狎狎狎棹棹狎狎狎狎狎膨棹膨棹棹狎棹狎狎狎狎且嵌棹灌狎狎起藻狎狎棹狎棹狎狎狎等棹棹棹禩狎大贯膨棹狎膨狎自前存茬他的全棹但你讳狎膨狎棹狎狎狎膨下膨膨洒膨膨锻店但我绞讲打攒攒灌间攒攒攒攒镒

**Comment by yeyupiaoling** [comment]
就算不准，也不至于输出这样的，最起码ctc_greedy也会删除相邻重复的字符。模型和归一化文件都没有修改吗？

**Comment by wl-junlin** [comment]
> 就算不准，也不至于输出这样的，最起码ctc_greedy也会删除相邻重复的字符。模型和归一化文件都没有修改吗？

是啊，都没改，解压放到了对应的目录。两个音频都是一块测的，也不知道为什么会输出这样。

**Comment by wl-junlin** [comment]
[test.tar.gz](https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/files/6922029/test.tar.gz)
这是音频文件
