### ISSUE TITLE
index.html是什么

### ISSUE THREAD

**Issue by VisonYin** [yeyupiaoling/PaddlePaddle-DeepSpeech#58]
在启动前需要修改index.html中的请求url，把url改为加上读者服务器的IP即可。请问这个index.html是什么啊。

**Comment by yeyupiaoling** [comment]
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/e0054e51afa4e6431e3c159eb8f3a54de5965b71/templates/index.html#L28

**Comment by VisonYin** [comment]
谢谢
