### ISSUE TITLE
python3.8 export_model.py   模型不知道出现什么问题了

### ISSUE THREAD

**Issue by YouLei0106** [yeyupiaoling/PaddlePaddle-DeepSpeech#59]
/usr/local/python3.8.8/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/usr/local/python3.8.8/lib/python3.8/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
W0809 13:46:54.392204 22480 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 11.0, Runtime API Version: 10.2
W0809 13:46:54.427165 22480 device_context.cc:372] device: 0, cuDNN Version: 8.0.
Traceback (most recent call last):
  File "export_model.py", line 37, in <module>
    ds2_model = DeepSpeech2Model(vocab_size=data_generator.vocab_size,
  File "/data/Watermark_detection/PaddleDetection/ASR_Speech/PaddlePaddle-DeepSpeech-master/model_utils/model.py", line 86, in __init__
    self.init_infer_program()
  File "/data/Watermark_detection/PaddleDetection/ASR_Speech/PaddlePaddle-DeepSpeech-master/model_utils/model.py", line 434, in init_infer_program
    self.infer_exe.run(startup_prog)
  File "/usr/local/python3.8.8/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/python3.8.8/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/python3.8.8/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1098, in run
    return self._run_impl(
  File "/usr/local/python3.8.8/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1230, in _run_impl
    return self._run_program(
  File "/usr/local/python3.8.8/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1327, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
OSError: (External)  Cublas error, `CUSOLVER_STATUS_INTERNAL_ERROR`. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.  (at /paddle/paddle/fluid/platform/device_context.h:264)

**Comment by yeyupiaoling** [comment]
好像是CUDA报错了，你安装的是哪个版本，命令看一下。

**Comment by YouLei0106** [comment]
> 好像是CUDA报错了，你安装的是哪个PaddlePaddle版本，命令看一下。

paddlepaddle-gpu 2.0.1
![Dingtalk_20210809141318](https://user-images.githubusercontent.com/56539082/128666323-3d732469-f856-4adc-aa94-7ed830d7d7fe.jpg)

**Comment by yeyupiaoling** [comment]
你的CUDA版本呢？你先测试一下你的PaddlePaddle环境能否使用。

**Comment by YouLei0106** [comment]
python -m pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple
安装上这个，cuda10.2的
![Dingtalk_20210809142511](https://user-images.githubusercontent.com/56539082/128667356-b30cb20a-164f-4ab6-af7a-f00a6918e265.jpg)

**Comment by YouLei0106** [comment]
> 库达？

![Dingtalk_20210809175754](https://user-images.githubusercontent.com/56539082/128689524-c17b4bb2-844e-45e9-8e78-6a6e796e5ff1.jpg)
这个是什么问题？？

**Comment by YouLei0106** [comment]
> 你的CUDA版本呢？ 你先测试一下你的PaddlePaddle环境能否使用。

<img width="648" alt="3522a8af6df5b2b1a97d25ccc12c080" src="https://user-images.githubusercontent.com/56539082/128817891-52d52025-fa51-498e-a1f0-6c677e146a92.png">
大神，这个模型你是一个数据集训练的还是那三个数据一起集训练出来的

**Comment by yeyupiaoling** [comment]
不止，好多数据混在一起的。
