### ISSUE TITLE
docker 环境问题

### ISSUE THREAD

**Issue by Li-kewei** [yeyupiaoling/PaddlePaddle-DeepSpeech#6]
您好，我使用您提供配置docker的教程，但遇到：

E1210 12:48:08.426810  4204 pybind.cc:1261] Cannot use GPU because there is no GPU detected on your machine.

**Comment by yeyupiaoling** [comment]
@Li-kewei 你的机器有GPU吗？有没有安装显卡驱动？命令nvidia-smi看看。

**Comment by Li-kewei** [comment]
> @Li-kewei 你的机器有GPU吗？有没有安装显卡驱动？命令nvidia-smi看看。

非常感谢您的回复。我的机器安装了显卡驱动，可以正常使用GPU，但使用docker容器（root）时，不能使用nvidia-smi

**Comment by yeyupiaoling** [comment]
@Li-kewei 要在docker上使用NVIDIA显卡，要安装nvidia-docker。
这个教程可以帮到你：https://yeyupiaoling.blog.csdn.net/article/details/83052060#t13

**Comment by yeyupiaoling** [comment]
@Li-kewei 我更新了文档，这个有教如何安装nvidia-docker
