### ISSUE TITLE
Out of memory error on GPU 0.

### ISSUE THREAD

**Issue by YYJavaGit** [yeyupiaoling/PaddlePaddle-DeepSpeech#60]
本地虚拟环境运行
```
(DeepSpeech) root@pc:/opt/PaddlePaddle-DeepSpeech# CUDA_VISIBLE_DEVICES=0,1 python train.py
-----------  Configuration Arguments -----------
augment_conf_path: ./conf/augmentation.config
batch_size: 16
dev_manifest: ./dataset/manifest.test
init_from_pretrained_model: None
learning_rate: 5e-05
max_duration: 15.0
mean_std_path: ./dataset/mean_std.npz
min_duration: 1.0
num_conv_layers: 2
num_epoch: 200
num_rnn_layers: 3
output_model_dir: ./models
rnn_layer_size: 2048
share_rnn_weights: False
shuffle_method: batch_shuffle_clipped
test_off: False
train_manifest: ./dataset/manifest.train
use_gpu: True
use_gru: True
vocab_path: ./dataset/zh_vocab.txt
------------------------------------------------
dataset/manifest.noise不存在，已经忽略噪声增强操作！
[2021-08-10 10:52:37.536839] 训练数据数量：141316

W0810 10:52:37.726949 31179 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 10.2
W0810 10:52:37.729698 31179 device_context.cc:422] device: 0, cuDNN Version: 7.6.
W0810 10:52:50.697477 31331 operator.cc:242] mul raises an exception paddle::memory::allocation::BadAlloc, ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 165.586182MB memory on GPU 0, 5.866455GB memory has been allocated and available memory is only 67.937500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
W0810 10:52:50.698271 31332 operator.cc:242] mul raises an exception paddle::memory::allocation::BadAlloc, ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 165.586182MB memory on GPU 0, 5.866455GB memory has been allocated and available memory is only 67.937500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    main()
  File "train.py", line 90, in main
    train()
  File "train.py", line 85, in train
    test_off=args.test_off)
  File "/opt/PaddlePaddle-DeepSpeech/model_utils/model.py", line 316, in train
    return_numpy=False)
  File "/opt/anaconda3/envs/DeepSpeech/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/opt/anaconda3/envs/DeepSpeech/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/opt/anaconda3/envs/DeepSpeech/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/opt/anaconda3/envs/DeepSpeech/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1252, in _run_impl
    return_merged=return_merged)
  File "/opt/anaconda3/envs/DeepSpeech/lib/python3.7/site-packages/paddle/fluid/executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
RuntimeError: ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 165.586182MB memory on GPU 0, 5.866455GB memory has been allocated and available memory is only 67.937500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)

pci信息 NVIDIA Corporation GP104 [GeForce GTX 1060 6GB]
(DeepSpeech) root@pc:/opt/PaddlePaddle-DeepSpeech# lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 05)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) (rev 05)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation 200 Series/Z370 Chipset Family USB 3.0 xHCI Controller
00:14.2 Signal processing controller: Intel Corporation 200 Series PCH Thermal Subsystem
00:16.0 Communication controller: Intel Corporation 200 Series PCH CSME HECI #1
00:17.0 SATA controller: Intel Corporation 200 Series PCH SATA controller [AHCI mode]
00:1c.0 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #7 (rev f0)
00:1f.0 ISA bridge: Intel Corporation 200 Series PCH LPC Controller (B250)
00:1f.2 Memory controller: Intel Corporation 200 Series/Z370 Chipset Family Power Management Controller
00:1f.3 Audio device: Intel Corporation 200 Series PCH HD Audio
00:1f.4 SMBus: Intel Corporation 200 Series/Z370 Chipset Family SMBus Controller
01:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1060 6GB] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)


这是用docker测试的
root@pc:~# sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
Tue Aug 10 01:06:29 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 35%   37C    P8     9W / 180W |    224MiB /  6075MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
请问为什么会这样

**Comment by YYJavaGit** [comment]
CUDA_VISIBLE_DEVICES=0也是一样的结果
(DeepSpeech) root@pc:/opt/PaddlePaddle-DeepSpeech# CUDA_VISIBLE_DEVICES=0 python train.py
-----------  Configuration Arguments -----------
augment_conf_path: ./conf/augmentation.config
batch_size: 16
dev_manifest: ./dataset/manifest.test
init_from_pretrained_model: None
learning_rate: 5e-05
max_duration: 15.0
mean_std_path: ./dataset/mean_std.npz
min_duration: 1.0
num_conv_layers: 2
num_epoch: 200
num_rnn_layers: 3
output_model_dir: ./models
rnn_layer_size: 2048
share_rnn_weights: False
shuffle_method: batch_shuffle_clipped
test_off: False
train_manifest: ./dataset/manifest.train
use_gpu: True
use_gru: True
vocab_path: ./dataset/zh_vocab.txt
------------------------------------------------
dataset/manifest.noise不存在，已经忽略噪声增强操作！
[2021-08-10 11:03:20.146732] 训练数据数量：141316

W0810 11:03:20.336999  6913 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 10.2
W0810 11:03:20.339776  6913 device_context.cc:422] device: 0, cuDNN Version: 7.6.
W0810 11:03:33.292879  7077 operator.cc:242] mul raises an exception paddle::memory::allocation::BadAlloc, ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 165.586182MB memory on GPU 0, 5.866577GB memory has been allocated and available memory is only 67.812500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
W0810 11:03:33.293866  7076 operator.cc:242] mul raises an exception paddle::memory::allocation::BadAlloc, ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 165.586182MB memory on GPU 0, 5.866577GB memory has been allocated and available memory is only 67.812500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    main()
  File "train.py", line 90, in main
    train()
  File "train.py", line 85, in train
    test_off=args.test_off)
  File "/opt/PaddlePaddle-DeepSpeech/model_utils/model.py", line 316, in train
    return_numpy=False)
  File "/opt/anaconda3/envs/DeepSpeech/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/opt/anaconda3/envs/DeepSpeech/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/opt/anaconda3/envs/DeepSpeech/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/opt/anaconda3/envs/DeepSpeech/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1252, in _run_impl
    return_merged=return_merged)
  File "/opt/anaconda3/envs/DeepSpeech/lib/python3.7/site-packages/paddle/fluid/executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
RuntimeError: ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 165.586182MB memory on GPU 0, 5.866577GB memory has been allocated and available memory is only 67.812500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)

**Comment by yeyupiaoling** [comment]
@YYJavaGit 你自己都包错误找出来了，显存不足。

**Comment by yeyupiaoling** [comment]
设置更小的batch_size

**Comment by YYJavaGit** [comment]
好的我试试

**Comment by yeyupiaoling** [comment]
你的显存有点小，才6G

**Comment by YYJavaGit** [comment]
add_arg('batch_size',       int,    4,     "训练每一批数据的大小")

**Comment by yeyupiaoling** [comment]
至少11才行，这个分支，

**Comment by yeyupiaoling** [comment]
>add_arg('batch_size', int, 4, "训练每一批数据的大小")

batch_size太小容易导致模型梯度爆炸。

**Comment by YYJavaGit** [comment]
呃呃那我好像搞不了啦，工作站都在跑别的数据

**Comment by YYJavaGit** [comment]
好吧，感谢感谢 @yeyupiaoling

**Comment by yeyupiaoling** [comment]
新分支显存需求低一些，但是文档还没完成

**Comment by YYJavaGit** [comment]
我只是想弄个语音识别服务器，不想训练模型

**Comment by YYJavaGit** [comment]
我没找到比较好的方案

**Comment by yeyupiaoling** [comment]
@YYJavaGit 那你就不训练啊，我都提供了模型下载的。

**Comment by YYJavaGit** [comment]
我以为需要先训练一遍才能用文末的模型，我下载一个试试
