### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by zcswdt** [yeyupiaoling/PaddlePaddle-DeepSpeech#62]
您好，我按照您的说明在docker 中安装了环境所需的包，执行的命令是 `python -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/`
但是当我在进行推理的时候还是会报错，如下，应该是soundfile没安装成功。我看了requirements中有大写的Soundfile，请问这个问题如何解决呢？谢谢了
![image](https://user-images.githubusercontent.com/43515926/130544103-aefec06f-c2ec-4a22-abc2-9611b04619a6.png)

**Comment by yeyupiaoling** [comment]
试试
```
sudo apt-get -y update
sudo apt-get install -y libsndfile1
```
