### ISSUE TITLE
大神求救！导出模型时报错

### ISSUE THREAD

**Issue by lsj0093** [yeyupiaoling/PaddlePaddle-DeepSpeech#65]
您好！python export_model.py --pretrained_model=./models/step_final/
后报错
![image](https://user-images.githubusercontent.com/75405573/130719179-dce5065d-f58f-41f1-9196-fb765bb09e71.png)

![image](https://user-images.githubusercontent.com/75405573/130719254-98516332-aa23-4e16-bab1-e854b58d8974.png)

**Comment by yeyupiaoling** [comment]
@lsj0093 你是用的不是同一个数据字典，也就是dataset目录下的文件。我提供的全部文件都要覆盖之前的文件。

**Comment by lsj0093** [comment]
我用的aishell这个数据集，然后也执行生成数据列表，计算均值和标准差，构建词汇表。最后训练出模型，评估没问题，导出模型就报错。大神，这个是什么问题啦？谢谢啦

**Comment by yeyupiaoling** [comment]
@lsj0093 你得检查一下用的是不是同一个模型和数据字典，如果都没有问题，把模型发给我，我试试。

**Comment by lsj0093** [comment]
我用的aishell这个数据集，然后也生成数据列表，计算均值和标准差，构成表。最后训练出模型，评估没有问题，导出模型就报的这个错。大神，这是什么问题啦？谢谢啦

**Comment by lsj0093** [comment]
> @lsj0093你得检查一下用的不是同一个模型和数据字典，如果都没有问题，就把模型看成我，我记错了。



> @lsj0093 你得检查一下用的是不是同一个模型和数据字典，如果都没有问题，把模型发给我，我试试。

怎么发你？发到哪呀？

**Comment by yeyupiaoling** [comment]
发我邮箱吧，yeyupiaoling@foxmail.com

**Comment by lsj0093** [comment]
> 发我邮箱吧，[yeyupiaoling@foxmail.com](mailto:yeyupiaoling@foxmail.com)

已发

**Comment by yeyupiaoling** [comment]
不仅仅是模型参数啊，还要数据字典，这是配套的，不能混着用。

**Comment by lsj0093** [comment]
> 不仅仅是模型参数啊，还要数据字典，这是配套的，不能混着用。

数据字典怎么弄？

**Comment by yeyupiaoling** [comment]
执行这个生成的：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/release/1.0/tools/build_vocab.py

**Comment by lsj0093** [comment]
> 执行这个生成的：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/release/1.0/tools/build_vocab.py

tools里面那3个都执行过的

**Comment by yeyupiaoling** [comment]
那把生成的文件发给我

**Comment by lsj0093** [comment]
> 那把生成的文件发给我

我把那些生成文件都删了，数据集也删了重新下载，下载还需要7个小时

**Comment by yeyupiaoling** [comment]
。。。。，用训练下载很快

**Comment by yeyupiaoling** [comment]
你用我提供的模型和相关文件试试吧

**Comment by lsj0093** [comment]
> 你用我提供的模型和相关文件试试吧

也用过，不行。epoch_19那个

**Comment by lsj0093** [comment]
> 你用我提供的模型和相关文件试试吧

非常感谢大神，我明天再试试

**Comment by yeyupiaoling** [comment]
你没替换原来的生成的文件吗。dataset目录下的

**Comment by lsj0093** [comment]
> 你没替换原来的生成的文件吗。dataset目录下的

这回dataset下面删干净重新弄试试
