### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 1234zhang5678** [yeyupiaoling/PaddlePaddle-DeepSpeech#66]
我自己安装的paddle2.1.1里面的fluid.core里没有train时使用的函数

**Comment by yeyupiaoling** [comment]
现在是否正常了？

**Comment by 1234zhang5678** [comment]
我拿CPU跑的，太慢了。我下了已经训练好的模型参数orz

**Comment by yeyupiaoling** [comment]
用CPU跑？是个狠人

**Comment by 1234zhang5678** [comment]
也是没gpu
大佬知道怎么对这个模型的输入做损失值的反向传播么

**Comment by yeyupiaoling** [comment]
这是Paddle内部函数就实现的，不需要我们写

**Comment by 1234zhang5678** [comment]
![微信图片_20210910161617](https://user-images.githubusercontent.com/89519769/132822873-695c66d9-df01-40d9-a4f1-73984a00f23e.png)

没学过，用的也是云里雾里的

**Comment by yeyupiaoling** [comment]
不需要用这个，你自己多看例子吧。
