### ISSUE TITLE
这是怎么回事，我用的提供的训练好了的模型

### ISSUE THREAD

**Issue by Rateofteasing** [yeyupiaoling/PaddlePaddle-DeepSpeech#67]
![image](https://user-images.githubusercontent.com/41779866/130958374-c6ed359b-bfd2-4b89-8aff-4b48c685ab8a.png)

**Comment by Rateofteasing** [comment]
![image](https://user-images.githubusercontent.com/41779866/131314342-ebfefe4d-ccb8-4d78-a992-6de7fc50104e.png)
大佬我按照你给我的链接。在setup.sh 命令的最后  python3 setup.py install --num_processes 4 报错

**Comment by yeyupiaoling** [comment]
我给你的是导出模型，你执行到哪里了？

**Comment by Rateofteasing** [comment]
![image](https://user-images.githubusercontent.com/41779866/131316816-11cd20c4-f6b8-425d-9434-22b23b2fd201.png)
我执行在这里。

**Comment by yeyupiaoling** [comment]
你不是到导出模型吗，执行这个，然后执行预测就好。
![image](https://user-images.githubusercontent.com/26297768/131317032-7efd3f25-f5c1-44b6-8732-294aba1fad77.png)

**Comment by Rateofteasing** [comment]
我直接用的你的模型，是不是不用导出模型 。csdn上面下载的模型。（1300小时）

**Comment by yeyupiaoling** [comment]
要导出的
![image](https://user-images.githubusercontent.com/26297768/131317395-21a2b479-01c5-4137-bcde-0c68fdf422d0.png)

**Comment by Rateofteasing** [comment]
看见了，谢谢大佬。

**Comment by Rateofteasing** [comment]
问一下大佬，你给出的这几个模型。最好的是不是自收集(超过1300小时)的这个

**Comment by yeyupiaoling** [comment]
是的，数据量越多越好

**Comment by Rateofteasing** [comment]
好的，谢谢大佬了
