### ISSUE TITLE
python2 中文编码问题

### ISSUE THREAD

**Issue by Li-kewei** [yeyupiaoling/PaddlePaddle-DeepSpeech#7]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-31: ordinal not in range(128)

**Comment by yeyupiaoling** [comment]
@Li-kewei 这个是哪里出现的问题，你添加一下编码支持就好

**Comment by Li-kewei** [comment]
> @Li-kewei 这个是哪里出现的问题，你添加一下编码支持就好

python2下，语音路径出现中文字符，文本为中文，在data_utils/data 278行读取路径是，编码出现问题。非常感谢您的回复

**Comment by yeyupiaoling** [comment]
@Li-kewei 解决了吗？没问题我就关闭这个issue了。
