### ISSUE TITLE
导出报错

### ISSUE THREAD

**Issue by Alvin-LH** [yeyupiaoling/PaddlePaddle-DeepSpeech#72]
您好，打扰了我用的thchs_30已经训练好的model，我执行导出模型，报错：
C:\Users\lihao\anaconda3\envs\py37\lib\site-packages\paddle\fluid\framework.py:5327: UserWarning: Skip loading for 'gru_5.b_0_moment2_0'. Because 'gru_5.b_0_moment2_0' not in the program.
  format(name)))
C:\Users\lihao\anaconda3\envs\py37\lib\site-packages\paddle\fluid\framework.py:5327: UserWarning: Skip loading for 'gru_5.b_0_beta1_pow_acc_0'. Because 'gru_5.b_0_beta1_pow_acc_0' not in the program.
  format(name)))
C:\Users\lihao\anaconda3\envs\py37\lib\site-packages\paddle\fluid\framework.py:5327: UserWarning: Skip loading for 'gru_5.b_0_beta2_pow_acc_0'. Because 'gru_5.b_0_beta2_pow_acc_0' not in the program.
  format(name)))
...........
C:\Users\lihao\anaconda3\envs\py37\lib\site-packages\paddle\fluid\framework.py:5327: UserWarning: Skip loading for 'gru_5.w_0_moment1_0'. Because 'gru_5.w_0_moment1_0' not in the program.
  format(name)))
C:\Users\lihao\anaconda3\envs\py37\lib\site-packages\paddle\fluid\framework.py:5327: UserWarning: Skip loading for 'gru_5.w_0_moment2_0'. Because 'gru_5.w_0_moment2_0' not in the program.
  format(name)))
C:\Users\lihao\anaconda3\envs\py37\lib\site-packages\paddle\fluid\framework.py:5327: UserWarning: Skip loading for 'gru_5.w_0_beta1_pow_acc_0'. Because 'gru_5.w_0_beta1_pow_acc_0' not in the program.
  format(name)))
C:\Users\lihao\anaconda3\envs\py37\lib\site-packages\paddle\fluid\framework.py:5327: UserWarning: Skip loading for 'gru_5.w_0_beta2_pow_acc_0'. Because 'gru_5.w_0_beta2_pow_acc_0' not in the program.
  format(name)))
C:\Users\lihao\anaconda3\envs\py37\lib\site-packages\paddle\fluid\framework.py:5327: UserWarning: Skip loading for 'learning_rate_0'. Because 'learning_rate_0' not in the program.
  format(name)))
[2021-09-06 18:40:21.935978] 成功加载模型：./models/param/50.pdparams
成功导出模型，模型保存在：./models/infer/

进程已结束，退出代码为 0

这样对最后的预测结果有影响吗，这样导出模型之后也可以预测，我自己录了几个语音效果不是很好，是因为导出模型这里的关系吗，谢谢

**Comment by yeyupiaoling** [comment]
导出模型不影响的，是thchs_30数据太小了

**Comment by Alvin-LH** [comment]
> 导出模型不影响的，是thchs_30数据太小了

谢谢你
