### ISSUE TITLE
master更新20210907最新代码报错

### ISSUE THREAD

**Issue by vienettalau** [yeyupiaoling/PaddlePaddle-DeepSpeech#73]
从git上直接拉最新的代码(”数据预处理改为FFT“提交的版本)，运行报错如下：
![53a13b817750e972dada4d97a383775](https://user-images.githubusercontent.com/72115224/132464664-9cc9a8e8-1986-4521-b845-abe0916606b7.png)

**Comment by yeyupiaoling** [comment]
@vienettalau 你用 就的模型文件，在新代码上运行。就模型在就分支上使用，新代码请使用新模型

**Comment by vienettalau** [comment]
我使用的是您8.31csdn发布的AIShell的模型，这个也要在分支版本上使用吗..

**Comment by yeyupiaoling** [comment]
那个有点小问题，昨天又更新了

**Comment by vienettalau** [comment]
现在csdn上好像只有8.31的..等能下载的时候，我再试一下，感谢！

**Comment by yeyupiaoling** [comment]
地址是不变的。你从新下载吧：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech#%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD
里面的要全部替换项目的

**Comment by vienettalau** [comment]
重新下载，运行没问题了。感谢！
