### ISSUE TITLE
合成语音数据 tools/generate_audio/models 下的三个模型，还有一个是什么？

### ISSUE THREAD

**Issue by 18148758389** [yeyupiaoling/PaddlePaddle-DeepSpeech#74]
> 
![QQ截图20210909150601](https://user-images.githubusercontent.com/30387771/132639167-b1530b34-0dbc-41c0-a331-6107460a54cb.png)

**Comment by yeyupiaoling** [comment]
@18148758389 就两模型，文档写错了，我该一下

**Comment by 18148758389** [comment]
![微信截图_20210909154100](https://user-images.githubusercontent.com/30387771/132643855-9930ba57-007c-4ee1-8e01-4e794fce1014.png)
请问一下，generate_audio.py  中的需要对 **models/parallel_wavegan_baker_ckpt_0.4/pwg_default.yaml** 进行操作，这个问题是在哪里生成的？求教

**Comment by 18148758389** [comment]
![微信截图_20210909154100](https://user-images.githubusercontent.com/30387771/132644315-686be32d-baf0-4559-9090-98006eb8904c.png)
@yeyupiaoling 执行  generate_audio.py 脚本，会对 models/parallel_wavegan_baker_ckpt_0.4/pwg_default.yaml 进行操作的，请问下这个 models/parallel_wavegan_baker_ckpt_0.4/pwg_default.yaml  这个文件是在哪里生成的？求教

**Comment by yeyupiaoling** [comment]
你下载那个两个模型之后，解压不就有了？
