### ISSUE TITLE
专有数据训练

### ISSUE THREAD

**Issue by yuanweihong** [yeyupiaoling/PaddlePaddle-DeepSpeech#77]
感谢作者的分享！我想用在特定领域的中文词汇训练来增强模型，是基于你训练好的模型来训练，还是需要下载所有数据然后合并我自制的数据从头开始训练？

**Comment by yeyupiaoling** [comment]
我觉得只使用我的模型作为预训练模型，然后单独训练你自己的数据就好

**Comment by yeyupiaoling** [comment]
不过合并在一起训练也是可以的。

**Comment by yuanweihong** [comment]
多谢答疑！期待作者早日分享超大数据集的模型。
