### ISSUE TITLE
复杂度问题

### ISSUE THREAD

**Issue by Li-kewei** [yeyupiaoling/PaddlePaddle-DeepSpeech#8]
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Cannot parse tensor desc
  [Hint: Expected desc.ParseFromArray(buf.get(), size) == true, but received desc.ParseFromArray(buf.get(), size):0 != true:1.] at (/paddle/paddle/fluid/framework/tensor_util.cu:527)
  [operator < load_combine > error]

**Comment by yeyupiaoling** [comment]
@Li-kewei 你是在执行哪一步出错的？
