### ISSUE TITLE
多个数据集分次训练

### ISSUE THREAD

**Issue by yuanweihong** [yeyupiaoling/PaddlePaddle-DeepSpeech#80]
请教下作者，如果我用多个数据集分次训练，数据字典文件zh_vocab.txt和保存均值和标准值得numpy文件mean_std.npz需要合并吗？如果需要如何合并？谢谢！

**Comment by yeyupiaoling** [comment]
为啥分次训练呢？不能一起训练？

**Comment by yeyupiaoling** [comment]
多次训练的模型也不能混在一起用啊。

**Comment by yuanweihong** [comment]
数据不是一次采集过来的咋办，难道每次都要从头开始训练吗？

**Comment by yeyupiaoling** [comment]
也不是从头开始，可以在之前模型的基础上，只训练几轮就好。最重要的是之前的词汇表中已经包含了当前的字符。
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/6bc16e7a446fa612aa87562cd8d382bbe1d7239c/train.py#L23

**Comment by yuanweihong** [comment]
好的，多谢指导！
