### ISSUE TITLE
启动训练提示显存不足

### ISSUE THREAD

**Issue by littlestone0806** [yeyupiaoling/PaddlePaddle-DeepSpeech#81]
![image](https://user-images.githubusercontent.com/42195561/133870885-27fbb8f9-8d7e-477b-bb3f-8ef54015a0ee.png)

**Comment by littlestone0806** [comment]
显卡是GTX1050Ti  4G版本的

**Comment by yeyupiaoling** [comment]
训练，最低要8G，正常要11G以上

**Comment by yeyupiaoling** [comment]
@littlestone0806 你直接下载我的模型使用就好，可以不用训练

**Comment by littlestone0806** [comment]
谢谢作者。如果用您提供的模型，在进行数据准备操作之后，接下来该做哪一步？我在做后续的操作时，总提醒我models文件夹下东西不全

**Comment by littlestone0806** [comment]
![image](https://user-images.githubusercontent.com/42195561/133871520-7ff7dba5-fd6e-4b85-aea0-afa327b3a8a3.png)
我下一步执行评估时报的错

**Comment by yeyupiaoling** [comment]
@littlestone0806 你看到日志错误信息了吗？你下载的文件放哪了？

**Comment by littlestone0806** [comment]
我把下载的thchs_30.gz放到了download_data目录，然后修改了thchs_30.py的路径，也运行了thchs_30.py，在dataset中生成test、train、npz文件也都没问题，但是执行下一步模型导出时python export_model.py --pretrained_model=./models/param/50.pdparams就提示这个
![image](https://user-images.githubusercontent.com/42195561/133872730-32661a05-7925-4502-a354-368781eaa6c4.png)

**Comment by littlestone0806** [comment]
我看了您的博客，说每训练一轮保存一次模型，模型保存在 DeepSpeech/models/ 目录下，会不会是我没有训练，所以在导出模型时报错？

**Comment by yeyupiaoling** [comment]
我说的是下载我提供的模型，你下载数据集是不行的。

导出模型命令如下，文档写错了：
```
python export_model.py --resume_model=./models/param/50.pdparams
```
