### ISSUE TITLE
训练过程中死机，如何接着训练

### ISSUE THREAD

**Issue by littlestone0806** [yeyupiaoling/PaddlePaddle-DeepSpeech#82]
作者您好。用了您的模型，成功跑起来了，感谢！想问一下，如果训练自己的模型，训练时死机了，这时models文件夹下已经生成了一些pdparams，下次再启动如何调用最后一次的pdparams训练？因为默认的还是从1开始

**Comment by yeyupiaoling** [comment]
通过这个参数指定你的模型路径，就可以恢复训练了。pdparams这个模型前面不是有个数字吗，它就会根据那个数恢复到第几个epoch

https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/1e3f0c633305c88133224c05d7079bebf09d8c73/train.py#L23
