### ISSUE TITLE
导出模型时遇到点问题

### ISSUE THREAD

**Issue by sutyd** [yeyupiaoling/PaddlePaddle-DeepSpeech#83]
C:\Program Files\anaconda\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
W0921 02:02:48.317266 13920 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.2
W0921 02:02:48.334275 13920 device_context.cc:422] device: 0, cuDNN Version: 7.6.
C:\Program Files\anaconda\lib\site-packages\paddle\fluid\framework.py:5325: UserWarning: Skip loading for 'batch_norm_0.b_0_moment1_0'. Because 'batch_norm_0.b_0_moment1_0' not in the program.
  warnings.warn((
C:\Program Files\anaconda\lib\site-packages\paddle\fluid\framework.py:5325: UserWarning: Skip loading for 'batch_norm_0.b_0_moment2_0'. Because 'batch_norm_0.b_0_moment2_0' not in the program.
  warnings.warn((
C:\Program Files\anaconda\lib\site-packages\paddle\fluid\framework.py:5325: UserWarning: Skip loading for 'batch_norm_0.b_0_beta1_pow_acc_0'. Because 'batch_norm_0.b_0_beta1_pow_acc_0' not in the program.
  warnings.warn((
C:\Program Files\anaconda\lib\site-packages\paddle\fluid\framework.py:5325: UserWarning: Skip loading for 'batch_norm_0.b_0_beta2_pow_acc_0'. Because 'batch_norm_0.b_0_beta2_pow_acc_0' not in the program.
  warnings.warn((
后面还有一大串一样的，模型最后也能导出来，但准确率只有30-50分，长语音几乎无法识别，短语音就只有几个老模子是对的。

**Comment by yeyupiaoling** [comment]
@sutyd 这一大串是正常的输出。
你用的音频是自己的吗？如果是自己的音频，准确率不高也正常，因为数据集很小，泛化能力不够。

**Comment by sutyd** [comment]
> @sutyd 这一大串是正常的输出。
> 你用的音频是自己的吗？如果是自己的音频，准确率不高也正常，因为数据集很小，泛化能力不够。

谢谢作者！
