### ISSUE TITLE
导出模型时报错

### ISSUE THREAD

**Issue by littlestone0806** [yeyupiaoling/PaddlePaddle-DeepSpeech#84]
![image](https://user-images.githubusercontent.com/42195561/134300362-5fd68482-aeb6-4b5a-adfd-e0c1bf9e18fa.png)
不管是下载作者提供的1300小时的模型，还是导出百度提供的官方模型，都显示这个报错。环境也按照作者提示的安装了，并且无报错

**Comment by yeyupiaoling** [comment]
@littlestone0806 你下载的是这个分支提供的模型，要在对应的分支上使用。
https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/tree/release/1.0

**Comment by littlestone0806** [comment]
![image](https://user-images.githubusercontent.com/42195561/134335651-b8b93dcf-9cf1-498c-adec-7351b3406d32.png)
下了对应的分支，也安装了2.1.1的paddlepaddle，环境也照着配置了，导出模型或者预测模型出现这个报错

**Comment by littlestone0806** [comment]
用了作者分享的1300小时模型成功导出，用百度官方的模型，就报上面的错误，可能是模型出了问题

**Comment by littlestone0806** [comment]
另外，在V1.0版本说明中，少了安装flask-cors的步骤，在最后运行infer_server.py会报缺少flask-cors

**Comment by yeyupiaoling** [comment]
>用了作者分享的1300小时模型成功导出，用百度官方的模型，就报上面的错误，可能是模型出了问题

我的项目，你怎么用百度官方的模型呢？模型结构都不一样。

**Comment by yeyupiaoling** [comment]
>另外，在V1.0版本说明中，少了安装flask-cors的步骤，在最后运行infer_server.py会报缺少flask-cors

这个库常见，直接`pip install flask-cors`安装就好。
