### ISSUE TITLE
训练出错

### ISSUE THREAD

**Issue by yuanweihong** [yeyupiaoling/PaddlePaddle-DeepSpeech#85]
您好！我使用您训练好的aishell模型，模型命名为0.pdparams，训练thchs30的数据，执行create_data.py 时将生成 mean_std.npz 和 zh_vocab.txt的代码屏蔽了。执行train的时候报错，错误如截图：
![2021-09-22 17-54-44屏幕截图](https://user-images.githubusercontent.com/4622169/134324027-93167589-7e84-47d8-98c4-0c8ddf3d03cc.png)

麻烦答疑解惑，多谢！

**Comment by yeyupiaoling** [comment]
你用的是最新代码吗？最新代码这个问题已经修复了。

**Comment by yuanweihong** [comment]
我重新check下，多谢及时回复！

**Comment by yuanweihong** [comment]
新代码正常运行：
W0923 02:55:52.573268  2212 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0923 02:55:52.577507  2212 device_context.cc:422] device: 0, cuDNN Version: 8.1.
[2021-09-23 02:55:55.209787] 成功加载模型：./models/param/0.pdparams
Train [2021-09-23 02:55:57.756228] epoch: [1/50], batch: [0/835], learning rate: 0.00050000, train loss: 115.767479, eta: 1 day, 5:27:35
Train [2021-09-23 02:56:52.984383] epoch: [1/50], batch: [100/835], learning rate: 0.00050000, train loss: 50.109375, eta: 5:28:15

![00107D6F](https://user-images.githubusercontent.com/4622169/134449051-550716ba-5fd3-46f3-a4ff-cbeef59136f4.png)
