### ISSUE TITLE
数据格式

### ISSUE THREAD

**Issue by yuanweihong** [yeyupiaoling/PaddlePaddle-DeepSpeech#87]
dataset/audio/wav/0975/T0055G0002S0050.wav 您好 请问 您 是 有 房子 出租 吗

请问annotation中如上的数据格式对训练有影响吗？汉字中间是不是不能有空格？麻烦解答下，多谢！

**Comment by yeyupiaoling** [comment]
在生数据列表的时候 自动去掉空格的
