### ISSUE TITLE
tune

### ISSUE THREAD

**Issue by wchuan163** [yeyupiaoling/PaddlePaddle-DeepSpeech#9]
tune.py中
add_arg('model_path',        str,  './models/srep_final',  应为step_final 
然后
PYTHONPATH=.:$PYTHONPATH CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python tools/tune.py 只有1个GPU起作用，这个会是哪里问题？

**Comment by yeyupiaoling** [comment]
>tune.py中
add_arg('model_path', str, './models/srep_final', 应为step_final

谢谢告知。

>PYTHONPATH=.:$PYTHONPATH CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python tools/tune.py 只有1个GPU起作用，这个会是哪里问题？

这个只能使用1个GPU的，因为是使用推理的方式，所以只能用一个GPU。不好意思，是我文档没有写好

**Comment by yeyupiaoling** [comment]
@wchuan163 问题解决了吗？解决了我就关闭这个issue了。

**Comment by wchuan163** [comment]
解决了，谢谢！
