### ISSUE TITLE
export_model报错了。麻烦看下

### ISSUE THREAD

**Issue by zhangyifei1** [yeyupiaoling/PaddlePaddle-DeepSpeech#91]
![图片](https://user-images.githubusercontent.com/28425091/134868271-2cde5abd-46a8-4afb-8d41-53a79615f781.png)

**Comment by yeyupiaoling** [comment]
你是不是把不同分支的模型混乱使用了

**Comment by zhangyifei1** [comment]
> 
> 
> 你是不是把不同分支的模型混乱使用了

是的，这个不可以混用么？还是需要注意那些东西？

**Comment by yeyupiaoling** [comment]
肯定不能啊，要不怎么会有两个分支

**Comment by zhangyifei1** [comment]
> 
> 
> 肯定不能啊，要不怎么会有两个分支

换了release分支，可以了，谢谢，
我用了1000个小时的开源数据+5个小时的自有数据，目前训练了30个epoch，cer在0.09左右。请问这种情况正常吗？如果要提升识别效果？增加开源数据or增加自有数据？

**Comment by yeyupiaoling** [comment]
错误率这么低了，应该不错了。
