### ISSUE TITLE
关于release分支tensorrt加速的报错

### ISSUE THREAD

**Issue by zhangyifei1** [yeyupiaoling/PaddlePaddle-DeepSpeech#92]
![图片](https://user-images.githubusercontent.com/28425091/135055425-6c15b38e-5d6a-4677-80c6-91a047173563.png)
大哥，我把use_tensorrt = True，然后就报了这个错，请问是什么问题？

**Comment by zhangyifei1** [comment]
> 
> 
> 这个不支持tensortt加速，新分支删除了这个参数，这个分支忘记修改了

感谢回答，这里还有两个问题，麻烦有空看下。
![图片](https://user-images.githubusercontent.com/28425091/135195358-d3f1b6ba-09c9-4ddc-b570-4906a8bc053f.png)

1、这里的归一化是不是应该是标准化。
2、这个数据预处理的过程加了标准化，
      ①因为std是训练数据算出来的，这样是不是会对预测数据有限制，来了新的数据集会影响效果。
      ②综上，为什么不让模型接收原始数据，把标准化过程放在network里面，让模型自己做呢？这个做有什么优点呢？

**Comment by yeyupiaoling** [comment]
标准化和归一化是一个意思。归一化的作用是对数据限制在[-1, 1]，具体你百度了解深度学习的归一化作用。
模型不知道这样输入操作的，这个是静态图。动态图我考虑一下是否可以。
