### ISSUE TITLE
Linux(Ubuntu)使用集束搜索解码，运行infer_server.py报错 No module named '_lzma'

### ISSUE THREAD

**Issue by vienettalau** [yeyupiaoling/PaddlePaddle-DeepSpeech#93]
使用环境：Linux-Ubuntu18.04
问题描述：
按照doc文档beam_search.md中所写，安装集束搜索(ctc_beam_search)【ctc_decoders】库；安装截图如下：
![安装ctcdecode库](https://user-images.githubusercontent.com/72115224/135189652-75c01b65-ea47-42f0-b2a4-7b1127e2176a.JPG)

后运行infer_server.py，报No module named '_lzma'。如下：
![运行infer_server文件报错lzma](https://user-images.githubusercontent.com/72115224/135189904-80fa48d1-c56a-460a-a677-bb2df2c42ca7.JPG)

求问这是什么问题啊...是我【ctc_decoders】库没安装成功吗？

**Comment by vienettalau** [comment]
是我安装python3.7的时候缺少解压工具？

**Comment by yeyupiaoling** [comment]
命令安装
```
pip install backports.lzma
```

**Comment by vienettalau** [comment]
感谢，已经解决了。
通过您说的pip install backports.lzma后，还是不行..后来，通过命令sudo apt-get install  lzma，和sudo apt-get install  liblzma-dev，再重新编译python后解决的。

还有一个问题...运行infer_path.py，最后返回的score(分数)，短语音分数不显示，长语音分段得分有的都是负数..

**Comment by yeyupiaoling** [comment]
应该都有输出得分的，

**Comment by vienettalau** [comment]
长语音识别分数有是负数。。
![长语音识别分数有负分数](https://user-images.githubusercontent.com/72115224/135214415-a94b4c08-0c68-4eb9-a04e-2715ab23cfed.JPG)

短语音识别分数为0
![短语音识别分数为0](https://user-images.githubusercontent.com/72115224/135214427-86c12836-e296-4a19-9d91-8e7c5dc67f17.JPG)
