### ISSUE TITLE
请教大佬如何在您的预训练模型基础上增强训练自己的模型

### ISSUE THREAD

**Issue by missslw** [yeyupiaoling/PaddlePaddle-DeepSpeech#99]
我想在您的free_st_chinese_mandarin_corpus(109小时)模型基础上加自己的语音训练新模型不知如何操作
train.py里这2个参数不知如何配置
add_arg('resume_model',            str,  './models/step_final/50.pdparams',    "恢复训练，当为None则不使用预训练模型")
add_arg('pretrained_model',        str,  './models/step_final',    "使用预训练模型的路径，当为None是不使用预训练模型")
求大佬赐教

**Comment by yeyupiaoling** [comment]
我修改文档了：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech/blob/master/docs/train.md#%E5%BE%AE%E8%B0%83%E6%A8%A1%E5%9E%8B

**Comment by missslw** [comment]
这个问题已经ok了，但是训练时间太长了，实在等不了这么长时间
![1633841209(1)](https://user-images.githubusercontent.com/92216343/136682569-301365ed-d8f2-49ff-b229-c42b69d3c535.png)
才30条语音，是不是我那里操作的不对
我是用download_data下载了您的原始数据，让后在后面加上我的30条数据
然后用create_data.py生成manifest.train和manifest.test，接着替换成您原有mean_std.npz和zh_vocab.txt
最后开始train.py，训练时间eta竟然要400多天，实在等不了，大佬帮看看哪里错了

**Comment by missslw** [comment]
另外一个问题就是set CPU_NUM=8，train.py会报alloc内存溢出，只能设小一点才能过，因为我gpu版没配通，暂时只能用cpu版，大佬看看这个有什么解决办法

**Comment by missslw** [comment]
那请问大佬，我用download_data下载了您的原始数据，让后在后面加上我的30条数据
然后用create_data.py生成manifest.train和manifest.test，接着替换成您原有mean_std.npz和zh_vocab.txt
最后开始train.py，这一系列操作对吗，有没有问题
训练数据量：102425，eta：464 days 这2个数据都是对的吗？如果换gpu能快多少呢？

**Comment by yeyupiaoling** [comment]
里面有三个数据集下载的程序，你下载是哪一个？

**Comment by missslw** [comment]
free_st_chinese_mandarin_corpus(109小时)是这个

**Comment by yeyupiaoling** [comment]
这个的话，如果是2080ti，这个应该是要一天。

**Comment by yeyupiaoling** [comment]
用CPU预测还行，训练必须要用GPU，因为速度那个慢

**Comment by yeyupiaoling** [comment]
我刚才看了你这个显卡的显存才4G太小了，一般需要11G以上

**Comment by missslw** [comment]
我按照您的说法操作了，但是用新训练的包做预测没任何提高，请大佬帮我看看哪里有错？我的操作如下：
1、我把我的wav加在了dataset\audio目录
2、在free_st_chinese_mandarin_corpus.txt文件末尾增加相应的数据
3、用create_data.py创建manifest.test、manifest.train、mean_std.npz、zh_vocab.txt
4、用您free_st_chinese_mandarin_corpus原有的mean_std.npz、zh_vocab.txt替换刚生成的mean_std.npz、zh_vocab.txt
5、将train.py中的'num_epoch'改为60，开始训练
6、用export_model.py将训练生成的60.pdparams导出为预测模型
7、用infer_server.py开始转语音为文字

**Comment by missslw** [comment]
是放在了manifest.train

**Comment by yeyupiaoling** [comment]
不用，你用那个训练，就是用那个。你的数据是多少？

**Comment by yeyupiaoling** [comment]
但是aishell数据量更多，可能使用微调效果更好也不一定。
或许你重新训练试试。
你的数据还是少了点
